falconry/falcon

falcon/api.py

Hi! Stumbled over an inconsistency in a docstring. Tried to fix it.

docs(API): Fix signature of process_request(...) in API docstring

---

doc/community/faq.rst
falcon/request.py

Update and polish the FAQ to reflect the latest updates to the 0.2.0 code
base, in anticipation of 0.2.0rc1.

doc(FAQ): Bring up to date with latest 0.2.0 code

---

doc/conf.py
doc/index.rst

Switch to using standard RTD theme for improved readability. Copy important
sidebar content to the index page.

doc: Switch to using standard RTD theme

---

README.md

Now that 2.0 is released we don't need this note.

Update README to remove note about 2.0

---

falcon/errors.py

Use super() where possible

---

falcon/request.py

feat(Request) Add default parameter to get_param

---

falcon/routing/compiled.py
tests/test_default_router.py

A few edge cases were not included in the test suite. Add additional tests
and fix any bugs that the additional tests uncover. Also test for the
detection and raising of error for conflicting routes to encourage
uniform behavior between routers in the future.

fix(Router): Fix some edge-case bugs in the new compiled router

---

falcon/request.py

Standardize the docstring, fix typos, and add whitespace to code to
enhance readability.

doc(Request): Fix up get_param_as_date docstring

---

falcon/api.py

Modify the _compose_status_response() function to no longer use getattr to get
the body for HTTPStatus. This will make the code more readable and more
performant.
As part of this work, rework _compose_error_response() to no longer call
_compose_status_response(), saving a few CPU cycles in that path as well. If
we ever end up needing to duplicate this code a third time, consider factoring
out into a separate helper function at that point.

perf(api): Optimize HTTPStatus handling

---

falcon/request.py
falcon/response.py

Fixes issue with ImportError in some rare cases.
IMO this is a six issue, but in this case it seems reasonable to work around it.
Applying the fix discussed in https://github.com/falconry/falcon/issues/556

fix(cookies): Fixed issue #556 ImportError from six

---

falcon/__init__.py

Hoist HTTPStatus into falcon top-level namespace

---

falcon/request.py

Move the docstrings for access_route and remote_addr to the class
docstring. Edit the text for clarity.

doc(Request): Edit access_route, remote_addr docstrings

---

doc/api/errors.rst
falcon/errors.py
tests/test_httperror.py

This patch was written by isaifee, then later updated with a few minor documentation tweaks by myself in preparation for merging.

feat(HTTPError): Add HTTPTooManyRequests exception

---

falcon/api.py
falcon/api_helpers.py
tests/test_httperror.py

The default error serializer can return JSON or XML depending upon the Accept header, so include this in the response's Vary header so that proxies and caches do not potentially serve the wrong representation.
This commit adds a resp argument to the error serializer, which will break existing serializers.
(I did wonder about putting the header addition in api.py, if body is not None, so as not to affect the parameters to the serializer, but a custom serializer may not want/need to have any change to the Vary header.)

fix(HTTPError): add Vary header to default error serializer

---

falcon/util/uri.py

Remove "pragma: no cover" comments along with a few lines of dead code
(that were consequently not covered by any tests).

test(util.uri): Remove pragmas and dead code

---

falcon/request.py
falcon/response.py
falcon/response_helpers.py
tests/test_wsgi.py

Improve performance of format_range by ~50%.

perf(Response): Optimize format_range

---

falcon/response.py
falcon/response_helpers.py
tests/test_cookies.py

Remove extraneous "no cover" pragmas, and add tests as necessary to get back to 100% coverage after doing so.

test: Improve code coverage

---

setup.py

Rebased #604 and made a couple of tiny tweaks for clarity and consistency.

chore(setup.py): DRY up setup.py external module selection for Cython

---

CHANGES.rst
doc/changes/1.0.0.rst

Add the 1.0.0 changelog from the docs to CHANGES.rst.

chore(changelog): Include 1.0.0 changelog in CHANGES.rst

---

doc/api/middleware.rst
falcon/api.py

doc(middleware): Document the new params argument for process_resource

---

AUTHORS
falcon/response.py
tests/test_cookies.py

feat(set_cookie): convert max-age value to int implicitly

---

README.rst
doc/user/install.rst

Edit installation instructions to match how 1.0.0 will be published on PyPI.

doc(install): Update PyPy and CPython instructions

---

tools/test-requires

add minimum version for coverage module
Fixes #806

chore(test-requires): add minimum version for coverage

---

falcon/responders.py
tests/test_headers.py

fix(Response): Default OPTIONS responder sets Content-Length to 0

---

falcon/http_error.py
tests/test_httperror.py

feat(HTTPError): Set title to status message if title is None

---

doc/api/errors.rst
falcon/errors.py
tests/test_httperror.py

Vesuvium http 414 error class

---

falcon/bench/bench.py

Change create_bench to support WSGI applications implemented as Python generators (i.e. that yield strings or bytes).

chore(bench.bench): allow benchmarking apps implemented as generators

---

falcon/api.py
tests/test_middleware.py

Rework the execution of middleware, responders, and related error
handling in API. This was necessary in order to fix a couple of
bugs (raising errors from resource methods doesn't change status for
middleware, middleware processing isn't always continued when an
instance of HTTPError or HTTPStatus is raised). Along the way,
minor optimizations were made to reduce CPU time in this portion
of the code (offsets additional try..except setup overhead).
Fixes #635

fix(API): Improve and optimize execution of middleware methods

---

docs/api/errors.rst
docs/conf.py
docs/ext/doorway.py
docs/ext/rfc.py
falcon/errors.py

docs(errors): Update error class docstrings per the latest RFCs

---

falcon/request.py
tests/test_query_params.py

feat(Request): Recognize "on" and "off" as boolean-like strings

---

CHANGES.rst
docs/changes/1.1.0.rst
falcon/request.py
falcon/testing/__init__.py
tests/test_query_params.py

fix(Request): Allow form posts for all methods except GET and HEAD

---

falcon/errors.py
falcon/http_error.py

doc(errors): Normalize docstring for title param, href_text

---

CHANGES.rst
docs/changes/1.1.0.rst
setup.cfg

doc(CHANGES.rst): Update changelog, tag_build in preparation for rc1

---

falcon/bench/bench.py
falcon/testing/client.py
tests/conftest.py
tests/dump_wsgi.py
tests/test_cookies.py
travis_scripts/install.sh
travis_scripts/run_tests.sh

Also fix Jython incompatibilities that were discovered in the process.

Fix tox errors due to new versions of flake8 and requests

---

docs/user/install.rst
docs/user/quickstart.rst
docs/user/tutorial.rst

I would like share with others Windows users this documentation which can help them easy start using Falcon framework on Windows machines.
I spent more that few hours to find out how to easy run Falcon examples on Windows. I suppose that is more than one person, which have the same problems as I had.

docs(User Guide): Add to the documentation Waitress server working with Falcon

---

falcon/responders.py
tests/test_after_hooks.py
tests/test_http_method_routing.py

fix(routing): Default OPTIONS responder should return 200, not 204

---

falcon/request.py
tests/test_req_vars.py

This is to fix issue : https://github.com/falconry/falcon/issues/933

added referer attribute to request

---

falcon/bench/dj/dj/settings.py

A community member (@AndrewBurdyug) mentioned this as a cleaner
solution.

chore(bench): Generate django secret on-demand

---

falcon/__init__.py
falcon/constants.py

Remove unnecessary complexity in Falcon's namespacing.

refactor: Remove "constants" package

---

docs/user/faq.rst

docs(faq): add a section on consuming JSON query string values

---

docs/user/tutorial.rst

a error on waitress

---

examples/look/tests/test_app.py
falcon/bench/dj/dj/urls.py
falcon/bench/queues/api.py
falcon/cmd/print_routes.py
falcon/media/handlers.py
falcon/request.py
falcon/response.py
falcon/util/__init__.py
tests/test_httperror.py
tests/test_utils.py

Deal with this: https://github.com/PyCQA/flake8-import-order/issues/107

style: Fix I202 Additional newline in a section of imports

---

docs/api/hooks.rst
falcon/hooks.py
tests/test_after_hooks.py
tests/test_before_hooks.py

Fixes #1141 
FYI: I got a 👍 from the requester via Gitter; they are cool with this approach.
Checked code coverage locally on my MBP:
```
TOTAL                                    2571      0    737      0   100%
```

feat(hooks): Allow for passing arguments to hooks

---

falcon/request.py
tests/test_query_params.py

feat(Request): Add get_param_as_uuid()

---

docs/user/tutorial.rst

Add a note detailing all supported HTTP methods for Responders, addresses #963

doc(tutorial): Add a note on all supported HTTP methods

---

falcon/api.py
tests/test_error_handlers.py
tests/test_example.py
tests/test_middleware.py

This is a breaking Change.
Closes: https://github.com/falconry/falcon/issues/763

refactor(error_handler): Reorder Custom ErrorHandler params

---

falcon/request.py
tests/test_options.py
tests/test_request_attrs.py
tests/test_uri_templates.py

Set the default to False #1267

fix(request): Change RequestOptions.strip_url_path_trailing_slash default

---

docs/_static/custom.css
docs/api/routing.rst
docs/changes/0.3.0.rst
falcon/api.py
falcon/routing/compiled.py
tests/test_custom_router.py
tests/test_default_router.py

This is a rebased version of #1252 plus some doc updates and method signature tweaks.

feat(api): Facilitate the overriding of the default method mapping logic

---

BACKERS.md
README.rst
docs/_content/sidebar-sponsors.html
docs/_templates/sidebar-sponsors.html

(Using the term "patron" is more in keeping with the non-commercial, community-oriented nature of the project.)

doc(sponsors): Add new sponsor and change wording from "sponsor" to "patron"

---

CHANGES.rst
docs/changes/2.0.0.rst
falcon/request.py
tests/test_middleware.py
tests/test_options.py
tests/test_query_params.py

Changed the default value of RequestOptions.keep_blank_qs_values to True

---

.gitignore
CHANGES.rst
docs/changes/2.0.0.rst
falcon/response.py
tests/test_response.py

Closes https://github.com/falconry/falcon/issues/1269

Add headers property to Response class

---

falcon/testing/client.py
falcon/testing/helpers.py
tests/test_utils.py
tests/test_wsgi.py

Attempt to address https://github.com/falconry/falcon/issues/1215

feat(testing): allow overriding host, remote_addr, and arbitrary environ variables

---

tests/test_request_media.py

ref https://github.com/falconry/falcon/issues/1234

test(media): add regression tests for accessing empty media twice

---

docs/api/hooks.rst
falcon/api.py
falcon/hooks.py
tests/test_after_hooks.py
tests/test_before_hooks.py

Fixes https://github.com/falconry/falcon/issues/1351 (solution path **(A)** -- see https://github.com/falconry/falcon/pull/1352#issuecomment-439998925).
I will add a note in the documentation, as well as a solution-specific unit test if we choose to tread this path **(A)**.

fix(hooks): apply resource-level hooks even to suffixed responders

---

falcon/api.py
falcon/response.py
tests/test_response.py

ref https://github.com/falconry/falcon/issues/1331

perf(API): revisit request-response cycle micro optimizations

---

.travis.yml
CHANGES.rst
docs/changes/2.0.0.rst
falcon/media/json.py
falcon/testing/resource.py
falcon/util/__init__.py
requirements/tests
tests/test_after_hooks.py
tests/test_before_hooks.py
tests/test_example.py
tests/test_media_handlers.py
tests/test_middleware.py
tests/test_query_params.py
tests/test_wsgiref_inputwrapper_with_size.py

This PR represents the proof-of-concept for custom JSON handling (#1206) and additional kwargs for `loads` and `dumps` (#1192). 
TODO:

feat(media) Initial Implementation of custom json handling

---

docs/index.rst

This is the highest priority item from https://github.com/falconry/falcon/issues/1423

docs: replace the obsolete front page code example with the one from https://falconframework.org

---

CHANGES.rst
docs/api/middleware.rst
docs/changes/2.0.0.rst
falcon/api.py
falcon/response.py
tests/test_middleware.py
tox.ini

feat(middleware): Implement request short-circuiting via Response.complete

---

docs/deploy/index.rst
docs/deploy/intro.rst
docs/deploy/nginx-uwsgi.rst
docs/index.rst

This is initial shot at some deployment documentation using uWSGI and NGINX. If you find this helpful, both content and writing style please let me know and I will get it polished. Please read through point out spelling / grammar errors, I have looked at it long enough, I can't see them any more.
My objective was not to have a fully comprehensive guide and I am a little hesitant to be giving advice for setting up uWSGI since it is such a dynamic piece of software. Regardless, I would look to others to supply comments / best practices / additional thoughts that would improve this... hopefully I can learn along the way. :)
Kindly, NZ

docs(deployment) Create uWSGI + NGINX Deployment Documents

---

CHANGES.rst
docs/changes/2.0.0.rst

chore: aggregate our stylish contributors for the upcoming 2.0 release

---

.gitignore
docs/conf.py
requirements/docs
tools/generate_dash.sh
tox.ini

doc(Dash): Getting Dash documentation working

---

.gitignore
docs/conf.py
requirements/docs
tools/generate_dash.sh
tox.ini

doc(Dash): Backporting Dash documentation generation to 2.0

---

BACKERS.md

Add additional backers. I created a new section at the bottom for one-time donors.
N/A

doc(BACKERS): Add additional backers (incl. one-time donors)

---

docs/_static/custom.css
falcon/hooks.py

This patch fixes a couple of formatting issues that were caused by recent updates to sphinx styles.
N/A

doc: Fix wrapping and spacing issues

---

docs/_newsfragments/1194-cors.feature.rst
docs/api/cors.rst
falcon/api.py

(Also updates other docs to Generalize to "all responses".)

doc(CORS): Add news fragment for issue #1194

---

.travis.yml
setup.py
tox.ini

Hi,
This `PR` enable `python` **3.8**
Closes #1587 
Regards,

Enable python 3.8

---

.travis.yml

See also the discussion on #1527

chore: Temporarily disable the hug gate due to breaking changes

---

docs/deploy/nginx-uwsgi.rst

Fixes listening IP address to 127.0.0.1:8080 to avoid confusion.
As I was reading the documentation on leveraging `uwsgi` for deploying Falcon I noticed a minor typo in the documentation. I fixed this typo which changes the documented listening IP address as `12.0.0.1:8080` to the correct `127.0.0.1:8080` address.
No related issues.
If you have *any* questions to *any* of the points above, just **submit and …

Fixes typo in listening IP address.

---

.travis.yml
README.rst

doc(README): update social media handles

---

setup.py

Replace deprecated imp module with importlib in setup.py
fix #1651

Replace deprecated imp module with importlib in setup.py

---

falcon/asgi/request.py

add a missing comma in `__slots__`
N/A

add missing comma in falcon.asgi.request.Request.__slots__

---

docs/api/routing.rst

Fix simple typo: walkthough -> walkthrough

---

docs/api/middleware.rst
falcon/app.py
falcon/app_helpers.py
falcon/asgi/app.py

Update the middleware docs to better address the new ASGI implementation.
#1358

ASGI: Update middleware docs

---

.travis.yml
tests/asgi/test_asgi_servers.py
tox.ini

test: Enable Windows gate on Travis CI

---

.travis.yml
falcon/asgi/response.py
falcon/media/handlers.py
falcon/testing/helpers.py
falcon/util/misc.py
falcon/util/sync.py

chore(mypy): fix mypy warnings & re-enable the mypy gate in Travis

---

docs/api/cors.rst
falcon/__init__.py
falcon/app.py
falcon/asgi/app.py
falcon/middlewares.py
tests/test_cors_middleware.py
tests/test_headers.py
tests/test_media_handlers.py
tests/test_middleware.py

Allows customization of the list of allowed origins, the list of
origins that support credential and the additional headers to expose
Closes #1719 

Improve cors middleware.

---

docs/_newsfragments/1730.breakingchange.rst
falcon/testing/client.py
tests/test_utils.py

feat(testing): change params_csv default to False to match RequestOptions.auto_parse_qs_csv

---

docs/api/media.rst
docs/user/recipes/index.rst
docs/user/recipes/pretty-json.rst

We've been debating this with @CaselIT on Gitter, so I decided to just go ahead and package my answers into a recipe.

docs(recipes): discuss prettifying JSON responses

---

falcon/response.py

Improve documentation for set_cookie domain and httponly parameter
Closes #947

docs(request): clarify domain and http only documentation

---

README.rst

Replaces what was rendered as a block quote into a code block.
N/A

Make xdg-open example a code block

---

.github/workflows/tests.yaml
tests/asgi/test_asgi_servers.py

chore(Actions): update workflows to use the now stable CPython 3.9

---

.github/workflows/create-wheels.yaml

Follow up to #1754 to avoid this error https://github.com/RalfG/python-wheels-manylinux-build/issues/26 when building linux wheels

chore: update wheel workflow to avoid LD_LIBRARY_PATH error

---

docs/user/faq.rst
docs/user/install.rst

~~_Note_: I haven't updated the [WebSocket FAQ item](https://falcon.readthedocs.io/en/latest/user/faq.html#does-falcon-support-websocket) yet, as @kgriffs is working on that atm.~~
**Edit**: I have just updated it here instead. Let me know what you think.

docs(FAQ): update FAQ to reflect new developments in Falcon 3.0

---

tools/check-vendored.sh

chore(vendor): adapt python-mimeparse version check to pip 20.3.1 output

---

tests/asgi/test_sync.py

test(test_sync): exaggerate race conditions to make tests more deterministic

---

.github/workflows/tests.yaml
tools/towncrier_draft.py
tox.ini

chore(towncrier): add a sanity check for rendering towncrier newsfragments

---

docs/_newsfragments/1597.bugfix.rst
falcon/cyutil/uri.pyx
falcon/request.py
falcon/util/uri.py
tests/test_query_params.py

fix(parse_query_string): only the first set of values for the same key are are split

---

.github/workflows/tests.yaml
tests/asgi/test_asgi_servers.py
tox.ini

test(ASGI): include hypercorn in ASGI server tests

---

setup.cfg
tests/conftest.py
tox.ini

chore(env): set the required Falcon envvars in conftest.py

---

.github/workflows/tests-emulated.yaml

Test run: https://github.com/falconry/falcon/actions/runs/473948191

chore: pin tox also for emulated s390x/arm64v8 tests

---

docs/user/install.rst
docs/user/tutorial-asgi.rst

docs(install,tutorial): improve app server installation docs + a couple of touch-ups for ASGI tutorial

---

docs/api/routing.rst
docs/user/faq.rst
docs/user/tutorial-asgi.rst

doc(asgi): edit ASGI tutorial and related docs for clarity and accuracy

---

.github/workflows/tests.yaml
.gitignore
e2e-tests/conftest.py
e2e-tests/server/__init__.py
e2e-tests/server/app.py
e2e-tests/server/chat.py
e2e-tests/server/hub.py
e2e-tests/server/ping.py
e2e-tests/static/index.html
e2e-tests/static/main.js
e2e-tests/static/style.css
e2e-tests/test_basic.py
e2e-tests/test_e2e.py
falcon/asgi/response.py
requirements/e2e
tox.ini

Closes #1576
These tests are very simplistic (for now), but I just wanted to get the ball rolling, as well as to write a somewhat realistic application to test our SSE and WebSocket affordances before the release.

test(E2E): add basic E2E tests for SSE & WebSocket

---

docs/_newsfragments/1871.bugfix.rst
falcon/util/misc.py
tests/test_utils.py

fix(to_query_str): properly quote query string parameters

---

falcon/asgi/app.py
tests/asgi/test_response_media_asgi.py

In response to @kgriffs' comment on Gitter:
> BTW I just realized that inlining `render_body()` prevents people from easily overriding that logic in a subclass but I guess we can wait to see if anyone actually needs to do that in practice.

fix(asgi.App): only inline Response.render_body() when it's safe to

---

.github/workflows/tests.yaml
docs/_newsfragments/1882.bugfix.rst
falcon/util/deprecation.py
tests/_wsgi_test_app.py
tests/test_wsgi_servers.py
tox.ini

fix(deprecation): do not rely on interpret-specific stack frame introspection

---

README.rst
docs/community/help.rst
docs/deploy/nginx-uwsgi.rst
docs/index.rst

docs: polish misc stuff before the impending major release

---

README.rst
docs/index.rst
docs/user/intro.rst

This patch tweaks the features list to bubble up Falcon's more unique value propositions.

doc: reorganize the features list

---

AUTHORS
CONTRIBUTING.md
docs/community/contribute.rst

@CaselIT feel free to add anything I might have missed.

docs(contributing): add Federico to the maintainers team

---

CONTRIBUTING.md
falcon/media/json.py

docs: tweak and fix misc issues

---

docs/api/cors.rst

This PR modified the comments in the CORS code to make it clearer that the two options are alternatives.
Fixes #1930

Clarify CORS options in code example (resolves #1930)

---

.github/workflows/tests.yaml
falcon/hooks.py
tox.ini

docs(hooks): fix a minor inconsistency in `falcon.after` docs

---

.github/workflows/create-wheels.yaml
CONTRIBUTING.md
docs/changes/3.1.0.rst
falcon/util/sync.py
setup.cfg
tests/asgi/test_ws.py
tox.ini

chore: add CI support for CPython 3.10 tooling, wheels

---

docs/user/faq.rst
e2e-tests/server/app.py
falcon/asgi/response.py

Small forgotten touch-ups from my notes.

chore: resurrect misc forgotten touchups

---

docs/user/faq.rst

This PR extends our FAQ with the answers that I provided on #1978.
Closes #1978

docs(FAQ): add an entry on blocked cross-origin request

---

docs/api/routing.rst
docs/api/status.rst
docs/user/tutorial.rst
falcon/media/validators/jsonschema.py

docs: improve HTTP status docs, fix an import issue in WSGI tutorial

---

docs/_newsfragments/1320.newandimproved.rst
docs/api/errors.rst
falcon/errors.py
falcon/media/validators/jsonschema.py
tests/test_validators.py

feat(validators): add a specialized exception class for media validation

---

docs/_newsfragments/1806.newandimproved.rst
falcon/testing/client.py
tests/asgi/test_asgi_conductor.py
tests/asgi/test_sse.py
tests/asgi/test_ws.py
tests/test_testing.py

feat(testing): add shorthand aliases to `simulate_*` methods

---

README.rst
docs/user/tutorial.rst

docs: fix typo

---

setup.cfg

chore: remove pip install warnings

---

.github/workflows/tests.yaml
docs/user/faq.rst

Complete example at https://gist.github.com/vytas7/4ab1317455318db05b309dae75ab1662

docs(FAQ): add ASGI version of direct upload to cloud

---

CONTRIBUTING.md
falcon/util/sync.py

CONTRIBUTING.md: Fix typo

---

docs/api/routing.rst
docs/changes/3.0.0.rst
docs/ext/private_args.py
docs/user/tutorial-asgi.rst
falcon/app.py
falcon/constants.py
falcon/hooks.py
falcon/http_error.py
falcon/inspect.py
falcon/request.py
falcon/response.py
falcon/routing/compiled.py
falcon/util/time.py
tests/asgi/test_scheduled_callbacks.py
tests/test_custom_router.py
tests/test_headers.py
tests/test_request_attrs.py

[`codespell --ignore-words-list=doesnt,geting,hist,statics -w .`](https://pypi.org/project/codespell)

chore: fix typos discovered by codespell

---

.github/workflows/create-wheels.yaml
.github/workflows/mintest.yaml
.github/workflows/tests.yaml
AUTHORS
CONTRIBUTING.md
docs/changes/4.0.0.rst
pyproject.toml
requirements/tests
setup.cfg
tox.ini

chore: formalize CPython 3.11 support

---

falcon/constants.py

Add media constant for 'image/bmp'.

Add MEDIA_BMP

---

.coveragerc
.github/workflows/create-wheels.yaml
.github/workflows/tests.yaml
tox.ini

+some CI fighting since we haven't run it in a while
Closes #2128

chore: drop support for `manylinux2010` binary wheels

---

docs/index.rst

Running the very first example in the documentation no longer results in a NameError. Additionally there is a link to the Quickstart for a full example.
N/A

docs(examples): improve code teaser in index page

---

docs/_newsfragments/2213.newandimproved.rst
docs/api/cookies.rst
falcon/testing/client.py

Follow-up on https://github.com/falconry/falcon/pull/2248

docs(cookies): polish docs for the `partitioned` cookie attribute

---

docs/_newsfragments/2253.misc.rst
falcon/asgi/app.py
falcon/asgi/ws.py
falcon/routing/static.py
falcon/testing/client.py
falcon/util/sync.py
tests/asgi/_asgi_test_app.py
tests/asgi/test_scope.py
tests/asgi/test_sync.py
tests/asgi/test_ws.py
tests/dump_asgi.py

Deprecating two asyncio aliases (`create_task` and `get_running_loop`) used in Falcon.
Fixes #2253 

refactor(util/sync): deprecate asyncio aliases

---

.github/workflows/create-wheels.yaml
.github/workflows/mintest.yaml
.github/workflows/tests-emulated.yaml
.github/workflows/tests-mailman.yaml
.github/workflows/tests.yaml

```shell
sed -i 's/checkout@v3/checkout@v4/g' *.yaml
```
```shell
sed -i 's/setup-python@v4/setup-python@v5/g' *.yaml
```

chore: update actions: `checkout` & `setup-python`

---

falcon/request.py

refactor(request): move function call outside try..except block

---

setup.cfg

Add `Typing :: Typed`  to Classifiers in setup.cfg
Closes: #2283

chore(setup): Add Typing :: Typed Trove classifier

---

docs/_newsfragments/2301.misc.rst
docs/_newsfragments/2301.newandimproved.rst
falcon/response.py
falcon/util/time.py
tests/test_cookies.py
tests/test_utils.py

chore: deprecate TimezoneGMT class

---

AUTHORS
docs/changes/4.0.0.rst
falcon/util/misc.py

Polishing minor details after merging #2246.
Also aggregated the 4.0 authors so far.

refactor(misc): clean up post-#2246

---

README.rst
docs/community/contributing.md
docs/user/faq.rst
docs/user/install.rst
docs/user/tutorial-asgi.rst
docs/user/tutorial-websockets.rst

docs(install): update the installation docs wrt PEP 517

---

docs/_newsfragments/2335.newandimproved.rst
docs/user/recipes/output-csv.rst
examples/recipes/output_csv_stream_asgi.py
examples/recipes/output_csv_stream_wsgi.py
examples/recipes/output_csv_text_asgi.py
examples/recipes/output_csv_text_wsgi.py
falcon/__init__.py
falcon/constants.py

Add csv and parquet media types to the constants.
- fix https://github.com/falconry/falcon/issues/2335

feat(constants): add CSV and Parquet media types

---

docs/api/media.rst
docs/changes/3.0.0.rst
docs/user/recipes/pretty-json.rst
falcon/asgi/request.py
falcon/media/validators/jsonschema.py
falcon/routing/static.py
falcon/testing/helpers.py
tests/asgi/_asgi_test_app.py
tests/asgi/_cythonized.pyx
tests/asgi/test_cythonized_asgi.py
tests/asgi/test_scheduled_callbacks.py
tests/asgi/test_scope.py
tests/asgi/test_ws.py
tests/test_headers.py
tests/test_middleware.py
tests/test_python_version_requirements.py
tests/test_validators.py

Fix some typos in this repo. Most of them are harmless, except the jsonschema properties (I suppose).
Checked by [typos](https://github.com/crate-ci/typos). If you like, I could create another PR to add it as a CI job.
N/A

style: fix typos in falcon,docs,tests

---

docs/_newsfragments/2470.newandimproved.rst
setup.py
tests/test_cython.py

perf(cython): revise the scope of cythonization

---

AUTHORS
docs/_newsfragments/2457.newandimproved.rst
docs/changes/4.1.0.rst
falcon/testing/client.py
tests/test_utils.py

Follow-up to https://github.com/falconry/falcon/pull/2471.

docs(towncrier): add a newsfragment for #2457

---

falcon/_typing.py
falcon/app.py
falcon/asgi/app.py

Falcon does not catch `BaseException` almost anywhere (nor it should). Update typing to reflect this fact.

fix(typing): change `BaseException` ➡️ `Exception`

---

docs/_newsfragments/2381.newandimproved.rst
falcon/app.py

(Also improve 1 newsfragment.)

refactor(App): simplify middleware initialization

---

falcon/request.py

Refactor the request.has_params(str) method to improve readability
Close #2488
- [ x ] Applied changes to both WSGI and ASGI code paths and interfaces (where applicable).
- [ x ] Added **tests** for changed code.
- [ x ] Performed automated tests and code quality checks by [running `tox`](https://falcon.readthedocs.io/en/stable/community/contributing.html#pull-requests).
- [ x ] Prefixed code comments with GitHub nick and an appropriate prefix.
- [ x ] Coding style is consistent with the rest of the framework.
- [ x ] Updated **documentation** for changed code.
- [ x ] Added docstrings for any new classes, functions, or modules.
- [ x ] Updated docstrings for any modifications to existing code.
- [ x ] Updated both WSGI and ASGI docs (where applicable).
- [ x ] Added references to new …

refactor(Request): rewrite has_param method to one-liner

---

docs/_newsfragments/2372.newandimproved.rst
docs/api/typing.rst
falcon/_typing.py
falcon/app.py
falcon/app_helpers.py
falcon/asgi/app.py
falcon/request.py
falcon/response.py
tests/test_typing.py

Fixes #2372.
CC @jkmnt @davetapley.

feat(typing): improve typing of custom req/resp type

---

.github/workflows/test-other.yaml
.github/workflows/tests.yaml
README.rst
docker/bench_py3.Dockerfile
docker/bench_py3_cython.Dockerfile
docker/bench_pypy3.Dockerfile
docs/changes/4.2.0.rst
docs/ext/cibuildwheel.py
docs/index.rst
docs/user/install.rst
docs/user/intro.rst
docs/user/tutorial-asgi.rst
falcon/asgi/reader.py
falcon/asgi/request.py
falcon/constants.py
pyproject.toml
requirements/bench
setup.py
tox.ini

chore(platform): drop Python 3.8 support

---

AUTHORS
docs/changes/4.2.0.rst
falcon/app.py
falcon/asgi/app.py

Also aggregate 4.2.0 contributors so far.

fix(typing): uniformly use middleware type generics
