falconry/falcon

- AUTHORS
- doc/api/middleware.rst
- doc/index.rst
- falcon/api.py
- falcon/api_helpers.py
- falcon/bench/queues/api.py
- tests/test_middlewares.py
Create a new middleware method process_resource that occurs after process_request and routing, and ensure that the resource object is accessible. Additionally, make the resource object available to process_response.
Issue #400
> feat(middleware): Add middleware method "process_resource"

- CONTRIBUTING.md
- doc/api/api.rst
- doc/api/middleware.rst
- doc/user/install.rst
- falcon/api.py
- falcon/api_helpers.py
- falcon/errors.py
- falcon/hooks.py
- falcon/http_error.py
- falcon/request.py
- falcon/request_helpers.py
- falcon/response.py
- falcon/response_helpers.py
- falcon/routing.py
- falcon/testing/base.py
- falcon/testing/helpers.py
- falcon/testing/resource.py
- falcon/testing/srmock.py
- falcon/util/misc.py
- falcon/util/structures.py
- falcon/util/uri.py
Unify the use of markup in docstrings, particulary relating to the use of
backticks and asterisks. Also clean up any remaining minor inconsistencies or
errors in the docstrings.
Closes #334
> doc(reference): Standardize docstring syntax

- doc/user/quickstart.rst
The quickstart documentation has an incorrect example for process_resource middleware.
> doc(middleware): Fix middleware interface in quickstart

- doc/api/hooks.rst
- doc/api/middleware.rst
- doc/conf.py
- falcon/api.py
Misc. tweaks to the docs in preparation for 0.2.0rc1, including:
* Edit middleware docs for clarity and correctness
* Use Warning or Tip headers instead of Note, where appropriate
* Update sphinx config regarding author and copyright
> doc: Minor tweaks to middleware docs and RTD template

- falcon/http_error.py
- tests/test_httperror.py
Correct the link text typo "documention" to "documentation". Also make the text more generic by removing the reference to "API".
> fix(HTTPError): Correct typo in default link text, make more generic

- falcon/api.py
Add missing backticks around `resp`, and add missing colon introducing
a sample code block.
> doc(API): Fix markup errors in docstrings

- README.md
- README.rst
- tests/test_example.py
The `process_response` method of `JSONTranslator` is missing the
`resource` argument in order to fully comply with the new middleware
feature.
Closes #443
> docs: Change complex example to match new middleware feature

- doc/api/middleware.rst
The middleware components page includes a tip that talks about modifying
req.uri. That is a read-only property. Instead, the tip should refer
to req.path.
Also clarify that middleware is executed based on the order of the list
that was passed to falcon.API via the middleware kwarg.
> doc(Middleware): Correct and clarify a few passages of text

- README.rst
Remove note about 0.2 since it is no longer relevant. This has already
been done for the Markdown version of the README.
> doc: Remove 0.2 notice from README (RST version)

- setup.py
six.PY2 is used several times in falcon, but that wasn't added to six until 1.4.0
> fix(dependencies): falcon needs at least six 1.4.0

- falcon/request.py
- falcon/util/uri.py
- tests/test_query_params.py
- tests/test_utils.py
Fix problem when client send json/full url percent-encoded in a query string.
Now make decode in parse_query_string rather than in the requests processing.
ex:
url=http%3A%2F%2Ffalconframework.org%3Ftest%3D1
json=%7B%22test1%22%3A%20%22data1%22%2C%20%22test2%22%3A%20%22data2%22%7D
> (fix)(utils/uri) change decode behavior for handle json/url values

- README.md
- README.rst
Using svgs for the badges produces a more consistent visual experience
when rendered.
> doc(README): Updating CI status badges to SVG

- doc/api/status.rst
Add verbose status constants to the RST docs so that developers can discover
them without having to use help().
See also #308
> doc(status): Document verbose status constants

- falcon/request.py
- tests/test_req_vars.py
The range attribute of the Request object now requires that the value be prefix with 'bytes='
Fix #387
This will be incompatible with previous code that did not prefix the range value with 'bytes='
remove strip()
> fix(request.range): Require bytes prefix for range

- doc/user/install.rst
> doc(install) Warn about python updates when using cython

- falcon/api.py
The docstring for the api class has info about middleware.
The part about resource middleware was a little non-descriptive.
Change to docstring
> docs(api): Add info to docstring about resource middleware

- tools/clean.sh
- tools/clean_cythoned.sh
- tox.ini
Modify clean_cythoned.sh to recusively delete compilation artifacts.
> chore(cython): Recusively remove compiled module files

- .gitignore
- .travis.yml
- CONTRIBUTING.md
- tests/test_middlewares.py
- tests/test_request_body.py
- tests/test_utils.py
- travis_scripts/install.sh
- travis_scripts/install_jython2.7.sh
- travis_scripts/run_tests.sh
~~Trying to see if I can get the tests to run with Jython on Travis. Haven't actually implemented Jython support fixes yet.~~ All tests run for me locally, now, except for coverage, which is not compatible with Jython.
Fixes https://github.com/falconry/falcon/issues/458
-  ~~make Jython tests run with tox~~ looks like there are still problems with support for virtualenv
- skip coverage tests for Jython -- doesn't cause Travis to fail, though, so maybe okay to just let it be?
> feat(general): support Jython 2.7rc2

- tox.ini
Change flake8 config in tox.ini to allow lines up to 99 characters
> style(pep8): Allow lines up to 99 characters

- falcon/request.py
- falcon/testing/helpers.py
- tests/test_req_vars.py
Change if-modified-since and if-unmodified-since headers to datetime
objects instead of strings.
BREAKING CHANGE: The 'date', 'if_modified_since', and 'if_unmodified_since'
request parameters are now returned as datetime.datetime objects and not strings
Fixes #254
> fix(Request): Return date headers as datetime objects

- doc/api/routing.rst
- falcon/api.py
- falcon/routing/__init__.py
- falcon/routing/compiled.py
- falcon/routing/util.py
- setup.py
- tests/test_default_router.py
- tests/test_uri_templates.py
This replaces the routing logic with a new, faster strategy based on on-the-fly
generation of Python code. As part of replacing the logic, the architecture has
been refactored to decouple routing from falcon.API, thereby making it possible
for users to easily replace the default router with their own.
Closes #114
Co-Authored-By: Kurt Griffiths <mail@kgriffs.com>
> feat(routing): New router architecture and faster default router

- falcon/api.py
- falcon/http_status.py
- tests/test_httpstatus.py
Add an HTTPStatus exception that is handled similarly to HTTPError in
terms of hooks and middleware, but does not pass through error handling.
Fixes #414
> feat(api) Add HTTPStatus exception for immediate response

- doc/api/cookies.rst
- doc/api/index.rst
- doc/user/tutorial.rst
- falcon/request.py
- falcon/response.py
- falcon/response_helpers.py
- falcon/util/__init__.py
- falcon/util/time.py
- tests/test_cookies.py
Add the following new helpers for setting and getting cookies
- `set_cookie(name : str, value : str, **cookie_params) -> None`
- `get_cookie(name : str) -> Morsel`
- ` get_cookies() -> List[Morsel]`
- `unset_cookie(name : str) -> None`
Cookies will - if set - be rendered and merged with headers in
_wsgi_headers. For responses that don't use cookies, there will
no performance hit, except for a single "if cookies is not None:"
check in the _wsgi_headers call.
Implementation use the http.cookies.SimpleCookie (py3) or
Cookie.SimpleCookie (py2) from the stdlib.
Might find extra speed in doing our own implementation.
Fixes #292
> feat(Response) Add cookie helpers

- falcon/request.py
- tests/test_query_params.py
A user requested a feature where a param could be automatically parsed into a date.
closes #293, supersedes #498
> feat(request): Add function to get param as date

- doc/api/routing.rst
- doc/user/tutorial.rst
- falcon/api.py
- falcon/routing/compiled.py
Clean up documentation regarding routing. Remove references to RFC 6570 and
mention the new support for complex paramterized path segments.
Fixes #161
> doc(Routing): Update documentation per new routing engine

- falcon/request.py
Hoist datetime methods so that they can be called directly, thus avoiding
an additional namespace lookup operation when calling them.
> perf(Request): Remove extra datetime namespace lookup

- falcon/response.py
Edit the docstring for clarity and accuracy. Remove unnecessary language
copy-pasted from the RFC.
> doc(Response): Clean up set_cookie() docstring

- doc/api/util.rst
- falcon/testing/helpers.py
- falcon/util/misc.py
- tests/test_utils.py
falcon.testing.httpnow was removed by a previous commit. Restore it as an
alias for the sake of backwards compatibility, placing the actual code
in a new function, falcon.util.http_now().
Also update the docs to refer to the utils directly under falcon.*, rather
than falcon.util.* to promote the fact that developers can access them
in that way.
> fix(testing): Restore httpnow

- falcon/routing/compiled.py
- tests/test_default_router.py
The DefaultRouter will now allow static routes to be placed before
simple variable ones.  Placing static routes after simple variable ones
still raises a ValueError since they would be unreachable.
> Fix DefaultRouter conflict bug

- falcon/request.py
- tests/test_headers.py
- tests/test_query_params.py
Modify req.get_header to raise HTTPMissingHeader and update the relevant
test to verify the fix.
Fixes #534
> fix(Request): get_header raises the wrong exception

- falcon/routing/compiled.py
- tests/test_default_router.py
1. The order routes are added should not matter
2. Ensure entire path is consumed before returning a matched route
Closes #535
> fix(DefaultRouter): Handle additional edge cases

- doc/api/routing.rst
- falcon/routing/__init__.py
- falcon/routing/util.py
- tests/test_uri_templates_legacy.py
Restore the compile_uri_template function to the routing module to
ensure backwards compatibility with custom routing engines that
rely on it.
Fixes #532
> fix(routing): Restore compile_uri_template

- doc/user/tutorial.rst
Add more detailed instructions on how to use msgpack as a serialization
alternative to the default JSON content_type, including installation of
required packages from PyPI.
Fixes #522
> doc(Tutorial): Improvements to the msgpack example

- falcon/errors.py
- tests/test_httperror.py
- tests/test_query_params.py
These errors may refer to form params, not just query string params. Adjust
the response message to the client to make it more generic, in order to
avoid confusion.
Also adjust docstrings for HTTPInvalidXXX and HTTPMissingXXX to be more
informative and consistent.
See issue #549
> fix: Make invalid, missing param error messages more generic

- doc/user/tutorial.rst
Hooks section in the Tutorial was a bit misleading because hooks interface in examples was outdated.
> doc(Tutorial): Fixed hooks interface in tutorial

- doc/user/tutorial.rst
- remove global hook code example
- add mention of middleware
- add reference link to middleware
> docs(tutorial): note depreciation of global hooks

- falcon/request.py
- falcon/response.py
- tests/test_headers.py
Previously there was no way to check if a header had been set on
a response, without accessing _headers which doesn't feel clean.
This commit adds a get_header method on the response object for
checking if a header is set.
> feat(response): Add get_header method

- falcon/errors.py
- tests/test_httperror.py
Based on RFC 7235, add challenges to HTTP Unauthorized to indicate
authentication scheme. A server generating a 401 must send a WWW-Authenticate
header field containing at least one challenge
BREAKING CHANGE: Add new parameter to the __init__ method of class HTTPUnauthorized
to add determine authentication scheme in the WWW-Authenticate header field when a
401 (Unauthorized) is generated
> Add support for setting the realm to the HTTPUnauthorized class

- doc/user/quickstart.rst
I went through the docs page by page and looked for where a class declaration was missing the new object inheritance.
> Updated quickstart examples to inherit from object (new-style classes)

- falcon/request.py
- falcon/util/misc.py
- tests/test_req_vars.py
- tests/test_utils.py
Update http_date_to_dt to support obsolete date formats per RFC 7231.
Fixes #255
> fix(util) Add support for obsolete HTTP date formats

- falcon/request.py
- falcon/util/misc.py
- tests/test_utils.py
Don't check for obsolete date formats by default. When obsolete date
formats are not enabled, avoid unnecessary processing time and data
structure instantiation.
> perf(request): Optimize HTTP date parsing

- setup.py
Jython does not support Cython, so there is no need to bother users
with a note about it during the installation process. Detect Jython
and supress the message in that case. Also, refactor the detection
logic in setup.py to be more readable and explicit.
> Do not display Cython note when installing under Jython

- AUTHORS
- falcon/response.py
- falcon/util/misc.py
- tests/test_cookies.py
- tests/test_utils.py
Modify the Response object to actually set the expires token for the cookie that is being unset to a point in the past, causing the browser to immediately remove the now-expired cookie, which will remove the cookie from future Request objects.
The previous behavior of Response's unset_cookie function was just to delete the given name from the SimpleCookie object if it existed. However, this causes a problem in that the browser is not told to remove the cookie on its side, causing all future Request objects to still contain the cookie that was supposed to have been unset/removed.
Co-Authored-By: Kurt Griffiths <mail@kgriffs.com>
> fix(Response): Instruct browser to remove cookies

- AUTHORS
- falcon/request.py
- tests/test_request_context.py
Moving the instantiation of Request context to the end of Request.__init__, so that all Request properties are set up and accessible from within a context_type function.
> fix(Request): context_type function raises AttributeError

- falcon/request.py
- falcon/util/misc.py
- falcon/util/uri.py
- tests/test_access_route.py
which is similar to Werkzeug but more powerful
Supported:
1. fetch from "Forwarded" header (defined by RFC7239)
2. fetch from "X-Forwarded-For" header
3. fetch from "X-Read-IP" header
4. fetch from wsgi "REMOTE_ADDR" header
Related to #539 and #598 
This pull-request is simply a duplicate of #599 but always rebased onto the latest origin/master. I don't want to lose any more comments due to the rebase. Please write your comment to #599.
> Add `access_route` and `remote_addr` to Request object

- CODEOFCONDUCT.md
- doc/community/contrib-snip.rst
Add an official code of conduct, and reference it in the docs.
> doc: Add code of conduct

- falcon/response.py
Expand the docstring for steam_len to provide information about what
the developer can expect will happen if they set stream but not
steam_len.
> doc(Request): Note what happends when stream_len is not set

- falcon/request.py
- falcon/request_helpers.py
- tests/test_request_body.py
- tests/test_wsgi.py
Fix two bugs with the wsgi.input wrapper that is used to normalize
behavior between wsgiref and production-class web servers:
1. Do not hang when reading with a size < Content-Length but the
stream has already been consumed.
2. If Content-Length is invalid or missing, assume no content and
still wrap the stream, rather than sometimes wrapping and sometimes
not.
Also, improve the tests to more cleanly shut down the wsgiref server
between tests so that the above can be tested in a more modular
fashion.
> fix(Request): Make wsgi.input wrapper more robust

- AUTHORS
- falcon/request.py
- falcon/response.py
- falcon/response_helpers.py
- tests/test_headers.py
- tests/test_req_vars.py
Rebased and squashed version of #570
> feat(req+resp): Add support for Content-Range units other than 'bytes'

- falcon/testing/base.py
Make `api` and `srmock` arguments to `TestBase.setUp`
As currently implemented, `API` and `testing.srmock.StartResponseMock`
objects are instantiated during `setUp`. This means subclasses either
need to throw away those instances, or eschew the `super` call.
> fix(testing.base.TestBase): parameterize api and srmock

- falcon/hooks.py
- tests/test_after_hooks.py
- tests/test_before_hooks.py
In order to maintain backwards-compatibility with old hooks that do
not accept a requests argument, the framework performs introspection
when attaching hooks and inserts shims as needed. The introspection
raises an error for hooks that have been defined via
functools.partial().
Fix this by adding support for partial methods and generally making
the introspection more explicit. Modify tests to cover all the different
cases.
> fix(hooks): Improve detection of requests arg

- falcon/api.py
- tests/test_custom_router.py
This allows for more routing customisation. For example, to build
an indexed router so we can reverse build URLs (good for DRY).
> feat(routing) Pass by kwargs from api.add_route to router.add_route

- .travis.yml
- travis_scripts/run_tests.sh
Migrate to using TOXENV per https://goo.gl/JrUSne.
> chore(tox): Use standard variable to determine tox environment

- doc/community/faq.rst
- doc/user/tutorial.rst
The Talons project has not become a general repository for
community add-ons, as originally envisioned. Remove from the
the tutorial to avoid confusion (based on community feedback.)
Also update the FAQ as follows:
* Remove mention of talons to allow for diversity in
the Falcon ecosystem
* Remove mention of specific "choices" that Falcon lets
you make regarding complementary libraries, since in
each case there are actually many more choices than
given, and the list only seems to belabor the point.
> Remove mention of the Talons project from the tutorial, update FAQ

- falcon/http_error.py
pylint has no way of knowing OptionalRepresentation is a mixin
that expects to be used along with HTTPError (which will provide
the description attribute).
> fix(OptionalRepresentation): Disable pylint no-member check

- .travis.yml
Start the slow Jython test first since it takes the longest to
complete; other tests can run in parallel. Also, run the relatively
quick pep8 and pylint jobs in parallel with the slower Jython and
py26 jobs.
> chore: Optimize Travis test order

- falcon/request.py
- tests/test_req_vars.py
In addition to 'application/x-msgpack', add support to Request.client_accepts_msgpack() for 'application/msgpack'.
Rebased version of #603
Closes #544
> feat(Request): Add support for 'application/msgpack'

- falcon/routing/compiled.py
- tests/test_default_router.py
- tests/test_uri_templates.py
Allow situation like this:
```python
api.add_route('/files/{file_id}', resource_1)
api.add_route('/files/{file_id}.{ext}', resource_2)
```
Which ValueError was raised due to only one var node was allowed whether
other nodes are complex or not. This fix changes the behaviour so now it
only applys to simple vars.
See #564
> fix(URI template): allow complex vars coexist with simple var

- falcon/api.py
- tests/test_httpstatus.py
- tests/test_middlewares.py
This allows middlewares to interact with route parameters.
BREAKING CHANGE: `process_resource` must now accept `params`
argument. Fix #612
I've arbitrated in favour of an API breaking change, because I think it's better to break API now (before 1.0) than to support useless legacy tricks, but of course this is to be discussed :)
> feat(middleware) Pass params to process_resource

- .coveragerc
- .gitignore
- .travis.yml
- CONTRIBUTING.md
- falcon/api.py
- falcon/http_error.py
- falcon/request.py
- falcon/testing/helpers.py
- falcon/util/misc.py
- falcon/util/uri.py
- setup.cfg
- tests/test_wsgi_errors.py
- tools/combine_coverage.sh
- tox.ini
Minimize the use of "pragma: no cover" by combining coverage results across multiple runs. Update CONTRIBUTING.md with instructions for checking coverage, etc. before submitting a PR.
> test: Migrate to combined test coverage

- falcon/request.py
- falcon/util/uri.py
- tests/test_access_route.py
- tests/test_wsgi.py
Tune performance of the Request.access_route property, while also
making error handling more consistent, in the case that a header value
is malformed. Also, add a test to ensure that wsgiref passes
REMOTE_ADDR in the environment dict, as has been observed in production
WSGI servers. This is necessary to ensure that Request.access_route's
fallback to REMOTE_ADDR makes sense.
> fix(Request): Improve access_route perf and error handling

- doc/api/cookies.rst
- doc/community/faq.rst
- falcon/response.py
Improve the documentation regarding cookies, esp. with respect to using the secure cookie attribute. Edit the prose for clarity and correctness. Replace double-quotes with single-quotes in code samples.
> doc(Cookies): Improve user guide, docstring, and FAQ

- falcon/util/uri.py
- tests/test_query_params.py
I tested malformed % on [Google Search](https://www.google.com/?q=%%20%25) and it works (interpret as "% %"). So I think for robust reason the best solution is just interpreting it like Google did since it's not ambiguous.
> Fixed #588: more robust when querystring contains malformed %

- falcon/api.py
- falcon/response.py
- tests/test_after_hooks.py
- tests/test_hello.py
- tests/test_middlewares.py
**Please review carefully** before merging. This is a significant change to the way the framework processes the response body.
---
Remove overhead from response body processing in API and Response.
BREAKING CHANGE: Response.body_encoded has been removed. The property was only intended to be used by the framework itself, so there should not be many apps using it.
To migrate the code, follow the example below:
Before:
```py
body = resp.body_encoded
```
After:
```py
if resp.body:
body = resp.body.encode('utf-8')
else:
body = b''
```
> perf(Response): Optimize response body processing

- doc/api/cookies.rst
- falcon/response.py
Remove mention of the "Cookie" header not allowing comma-delimited
folding. Also, wrap text in the last section of cookies.rst.
> doc(Cookies): Remove erroneous mention of "Cookie" header

- falcon/responders.py
When an invalid HTTP method is requested, or a path is requested for which there is no route configured, raise instances of HTTPError instead of directly manipulating the Response object. This makes it easier for applications to customize behavior in these cases.
> feat(API): Change error responders to raise instances of HTTPError

- tests/test_req_vars.py
A bug was fixed in python-mimeparse that caused an assertion to fail. A quality setting of "0.0" is now (correctly) treated as indicating that the associated media type is "not acceptable" by the client.
Adjust the tests accordingly.
> test(req.client_accepts): Fix invalid assertion based on q=0.0

- tox.ini
Add debug environments that accept pos args for specifying individual tests to run, and for passing options such as -s for use with pdb, ipdb, etc.
Also organize envs into sections with headers, and clean up the default envlist.
> test(tox): Add debug envs and organize into sections

- README.rst
- doc/community/contrib-snip.rst
- doc/community/contribute.rst
This PR simply clarifies what happens when you send your first e-mail to the mailing list.
(oh, and I also snuck a typo fix in there)
> doc(contrib-snip): Clarified mailing list subscription information

- doc/api/cookies.rst
- doc/api/index.rst
- doc/api/testing.rst
- doc/api/util.rst
- falcon/__init__.py
- falcon/api.py
- falcon/api_helpers.py
- falcon/response.py
- falcon/testing/__init__.py
- falcon/testing/base.py
- falcon/testing/helpers.py
- falcon/testing/resource.py
- falcon/testing/srmock.py
- falcon/testing/test_case.py
- falcon/util/structures.py
- falcon/util/uri.py
- tests/test_after_hooks.py
- tests/test_error_handlers.py
- tests/test_headers.py
- tests/test_hello.py
- tests/test_utils.py
- tox.ini
Add new testing classes for unittest-style test cases, based on lessons-learned using the original base class. Port several Falcon tests to use the new classes (the remainder to be ported in a subsequent release.) Include wsgiref valdiation by default.
DEPRECATION: The old base class and test resource have been deprecated and will be removed in a future release.
Fixes #689
> feat(testing): New test case base, result class, and test resource

- falcon/response.py
- tox.ini
Run pep8 with py27 since some code branches assume the unicode type is defined, and pep8 complains in those cases when running under py3.
> test: Force pep8 to run under py27

- .travis.yml
- CONTRIBUTING.md
- tools/doc-requires
- tox.ini
This PR adds tox and travis jobs for building documentation with sphinx.
It also modified `CONTRIBUTING.md` to show how to build it. :-)
Comments/suggestions welcome!
> chore(docs): Adds automated sphinx builds to tox and travis

- falcon/request.py
- tests/test_query_params.py
BREAKING CHANGE: 
Falcon will no longer automatically parse requests that have the content type `application/x-www-form-urlencoded`. This was done to avoid unintended side-effects that may arise from consuming the request stream. It also makes it more straightforward for applications to customize and extend the handling of form submissions.
Applications that require this functionality must re-enable it explicitly, by setting a new request option that was added for that purpose, e.g.:
```py
app = falcon.API()
app.req_options.auto_parse_form_urlencoded = True
```
Closes #719
> feat(Request): Add an option to toggle parsing of form params

- doc/api/middleware.rst
- falcon/api.py
- tests/test_middleware.py
Avoid the problem of having to include a `if resource is not None` check at the top of every process_resource() method body.
Closes #691
> fix(API): Skip process_resource() when no route is found

- falcon/api.py
- falcon/api_helpers.py
- falcon/bench/queues/api.py
- falcon/hooks.py
- falcon/routing/util.py
- tests/test_after_hooks.py
- tests/test_before_hooks.py
- tests/test_http_method_routing.py
- tests/test_httpstatus.py
Middleware components superseded global hooks in version 0.3 of the framework. By now, developers should have had enough time to migrate away from the deprecated feature. If not, they can continue using 0.3 until they are able to migrate.
BREAKING CHANGE
falcon.API no longer accepts `before` and `after` kwargs to specify global hooks. Applications should migrate any logic contained in global hooks to reside in middleware components instead.
Old:
```py
def do_something(req, resp, resource, params):
pass
app = falcon.API(before=[do_something])
```
New:
```py
class ExampleMiddlewareComponent(object):
def process_resource(self, req, resp, resource):
pass
```
Closes #384
> refactor(hooks): Remove deprecated global hooks feature

- falcon/routing/compiled.py
- tests/test_default_router.py
fix(falcon.routing.DefaultRouter): Do not mask variable path segments
When a single segment in a requested path can match more than one node at that branch in the routing tree, and the first branch taken happens to be the wrong one (i.e., the subsequent nodes do not match, but they would have under a different branch), do not mask the other branches that could result in a successful resolution of the requested path.
I chose to implement this by not immediately returning None when a branch prediction turns out to be false. Alternatively, I could have introduced functions but that would likely incur more overhead vs. performing a few additional node comparisons on the way back up the routing tree. I did, however, include a simple optimization that allows a "fast return" when only simple …
> fix(falcon.routing.DefaultRouter): Do not mask variable path segments

- .travis.yml
- falcon/http_error.py
- falcon/request.py
- falcon/testing/test_case.py
- tox.ini
pylint has not been catching anything that flake8 wouldn't also catch, and flake8 continues to improve, yielding pylint somewhat obsolete.
> chore: Remove pylint test

- tools/doc-requires
- tox.ini
Render docs using the RTD theme. Also, force a full rebuild of the docs
each time since sphinx sometimes doesn't detect docstring changes and
refuses to re-render them.
> fix(doc): Include RTD theme and force a full rebuild of docs

- CHANGES.rst
- README.rst
- doc/changes/1.0.0.rst
- doc/user/quickstart.rst
- falcon/errors.py
- tests/test_example.py
- tests/test_httperror.py
Update the complex example given in the quickstart and README so that
it now works in light of a breaking change to the HTTPUnauthorized
class. Note this breaking change in the changelog.
Closes #757
> doc(quickstart): Sync HTTPUnauthorized example with post-0.3 changes

- falcon/api.py
- falcon/routing/compiled.py
- tests/test_custom_router.py
- tests/test_default_router.py
The documentation for custom routers states that the find() method of the router should return None when no route is found. However, the API only allows for the (None, None, None) tuple. Add support for a simple None return value as well.
Closes #750
> fix(API): Allow the router's find() method to just return None

- falcon/request.py
- tests/test_query_params.py
> feat(Request): Allow 1 and 0 as valid boolean values in query string parsing

- setup.py
Add a tests_require field to the setup call so that running "setup.py test" doesn't fail if some packages aren't installed.
> fix(setup.py): Fix test dependencies

- tox.ini
This patch adds Python 3.5 to the list of environments in tox.ini.
> chore: adds py35 environment to tox.ini

- falcon/request.py
use try-catch instead of if..in for query string. try-catch is cheaper
and faster in Python
Fixes #637
> perf(Request): use try/catch instead of if..in for query string

- falcon/api.py
- falcon/errors.py
- falcon/request.py
- falcon/response.py
- falcon/testing/base.py
- falcon/testing/helpers.py
- falcon/testing/test_case.py
- falcon/util/__init__.py
- setup.py
- tests/test_before_hooks.py
- tests/test_cookies.py
- tests/test_example.py
- tests/test_hello.py
- tests/test_httperror.py
- tests/test_httpstatus.py
- tests/test_middleware.py
- tests/test_query_params.py
- tests/test_redirects.py
- tests/test_req_vars.py
- tests/test_request_context.py
- tests/test_uri_templates.py
- tests/test_utils.py
- tests/test_wsgi_errors.py
- tox.ini
PyCon 2016 sprint! Addresses #798.
Adds `flake8-import-order` plugin to the tox configuration file, along with all the reordering of existing imports in order to pass. Using the [Google import order style](https://github.com/public/flake8-import-order#configuration) as requested by @kgriffs.
Also adds `--application-import-names=falcon` as specified in #798.
> style(pep8): Add flake8-import-order plugin with import order changes (#798)

- tox.ini
For non-debug environments, we were not passing posargs through to nosetests.  This PR adds the option to pass arguments through to nosetests (for example, to run specific unit tests).
For example, to run the `TestHelloWorld` test case on py27, here's some sample output:
```bash
$ tox -e py27 -- test_hello:TestHelloWorld
GLOB sdist-make: /Users/fxfitz/github/falcon/setup.py
py27 inst-nodeps: /Users/fxfitz/github/falcon/.tox/dist/falcon-1.1.0.dev0.zip
py27 installed: You are using pip version 8.0.2, however version 8.1.2 is available.,You should consider upgrading via the 'pip install --upgrade pip' command.,coverage==4.0.3,ddt==1.0.1,extras==0.0.3,falcon==1.1.0.dev0,fixtures==1.4.0,linecache2==1.0.0,nose==1.3.7,pbr==1.8.1,pyrsistent==0.11.12,python-mimeparse==1.5.1,PyYAML==3.11,requests==2 …
```
> testing(tox): Adds missing posargs

- falcon/response.py
This patch updates docstring to explain that parameters set to Location and Content-Location headers shall be URI encoded per RFC 3986.
closes #687, closes #782
> docs: updates docstrings to explain uri encoding

- falcon/util/misc.py
- tests/test_utils.py
Added a utility function for looking up status messages by status code.
Additional work is still required to add either one or two new attributes to the response object.  There should be 3 altogether for consistency with the python requests library and the JavaScript XmlHttpRequest:
status  (e.g.  "404 Not Found")  <= already exists
status_code  (e.g. 404)  <= NEW (read / write)
reason  (e.g. "Not Found")  <= NEW  (read only)
> Issue #744 - added a utility function for looking up status messages

- falcon/request.py
- falcon/util/__init__.py
Pull requests are not passing in Travis due to failure of ```tox -e pep8```. This is due to
flake8 failing with F405 and F401 warnings. This pull request aims to fix the issue
Fixes #830
> fix(pep8): fix pep8 errors detected by flak8 (F405 and F401)

- falcon/request.py
- tests/test_query_params.py
The `req.get_param_as_dict()` function will allow users to get serialized JSON in the form of a dict.
Closes #789
Supersedes #791
> feat(Request): Implement get_param_as_dict()

- falcon/request.py
- falcon/util/misc.py
- falcon/util/uri.py
- tests/test_options.py
- tests/test_query_params.py
- tests/test_utils.py
In all cases, the options default to the previous behavior in order to avoid introducing any breaking changes.
* Add option to to_query_str to encode lists as multiple occurences of the same parameter.
* Add option to parse_query_string to not split comma-delimited values.
* Add an option to RequestOptions for toggling csv parsing.
Co-Authored-By: Daniel Schwarz <qwesda@me.com>
Co-Authored-By: Steven Ly <sly@openroad.ca>
Co-Authored-By: Kurt Griffiths <inbox@kgriffs.com>
Closes #749
> feat(util,Request): Add options to disable csv parsing of query params

- falcon/api.py
- falcon/routing/compiled.py
- tests/test_default_router.py
Raise ValueError if a field is found that is not a valid Python identifier. This prevents cryptic errors from being raised later on when requests are routed.
Co-Authored-By: Enzo Calamia <dev@sagebl.eu>
Co-Authored-By: Kurt Griffiths <inbox@kgriffs.com>
Closes #769
> fix(api.add_route): Validate uri template fields

- falcon/request.py
- falcon/response.py
- tests/test_response_context.py
Add a context property to the Response class, to mirror the context property that is already available on the Request class.
> feat(Response): Add context property to the Response class

- falcon/__init__.py
- falcon/api.py
- falcon/api_helpers.py
- falcon/errors.py
- falcon/hooks.py
- falcon/http_error.py
- falcon/http_status.py
- falcon/redirects.py
- falcon/request.py
- falcon/request_helpers.py
- falcon/responders.py
- falcon/response.py
- falcon/response_helpers.py
- falcon/routing/__init__.py
- falcon/routing/compiled.py
- falcon/routing/util.py
- falcon/status_codes.py
- falcon/testing/__init__.py
- falcon/testing/base.py
- falcon/testing/helpers.py
- falcon/testing/resource.py
- falcon/testing/srmock.py
- falcon/testing/test_case.py
- falcon/util/__init__.py
- falcon/util/misc.py
- falcon/util/structures.py
- falcon/util/time.py
- falcon/util/uri.py
- falcon/version.py
Co-Authored-By: Kurt Griffiths <inbox@kgriffs.com>
> doc: Add package and module docstrings for use in help()

- falcon/testing/test_case.py
- tests/test_headers.py
The requests library attempts to auto-detect the charset using chardet, but we just assume UTF-8 to avoid having to pull in another dependency.
> feat(testing.Result): Default to UTF-8 when charset is missing

- CONTRIBUTING.md
- README.rst
- falcon/bench/nuts/nuts/model/__init__.py
- falcon/bench/nuts/nuts/tests/test_functional.py
As per RTD's [blog post][1]:
> Starting today, Read the Docs will start hosting projects from
> subdomains on the domain readthedocs.io, instead of on
> readthedocs.org. This change addresses some security concerns around
> site cookies while hosting user generated data on the same domain as
> our dashboard.
[1]: https://blog.readthedocs.com/securing-subdomains/
> doc: Convert readthedocs links from *.org to *.io

- doc/api/testing.rst
- falcon/testing/__init__.py
- falcon/testing/client.py
- falcon/testing/helpers.py
- falcon/testing/test_case.py
Add free simulate_request, etc. functions that can be used without
requiring a unittest-style OO/inheritance model. Most notably, this
makes it easier to use pytest's more functional style when testing
falcon-based apps.
As part of this work, refactor the existing WSGI simulation logic
to layer on top of the free functions. Don't break backwards
compatibility.
Partially implements #16
> feat(testing): Add free functions for simulating WSGI requests

- falcon/http_error.py
Even if an error should not result in a representation being returned
in the body of the HTTP response, it may still be useful to serialize
the error for purposes of logging, without having to check the
representation flag first.
> fix(HTTPError): Remove asserts for self.has_representation

- falcon/api.py
- tests/test_error_handlers.py
Document and add tests to confirm the LIFO order that error handlers are visited when handling an exception.
> doc(API): Document the order in which error handlers are visited

- falcon/request.py
- falcon/response.py
- tests/test_slots.py
Add `__dict__` to the `__slots__` methods to the Request and Response classes
to make it them extensible via subclassing and adding custom attributes. I have
also added tests to make sure adding custom attributes do not break and raise
an `AttributeError`.
Fixes #785
> feat(request,response) add __dict__ to __slots__

- doc/api/testing.rst
- falcon/testing/__init__.py
- falcon/testing/client.py
- falcon/testing/test_case.py
Add a contextual wrapper for the simulate_* methods and a pytest
example demonstrating its use.
Also deprecate "api" in favor of "app" in TestCase, since these utils
can work with any WSGI app (not just those that express HTTP APIs). This
terminology makes TestCase more consistent with the new simulate_*
functions and with TestClient.
Finally, deprecate "api_class" in TestCase and update the docstring
for the testing module to demonstrate a less hacky alternative for
controlling the api instance type. As a bonus, this avoids having to
try and alias api_class (a class variable).
Partially implements #16
> feat(testing): Add TestClient class and a pytest example

- README.rst
- setup.py
- tests/test_deps.py
Document the difference between python-mimeparse and mimeparse, and
add a test to ensure Linux package maintainers, et al., are pulling
python-mimeparse, not mimeparse.
> test(mimeparse): Test for the correct version of mimeparse

- falcon/util/uri.py
- tests/test_utils.py
Detect a URI that is already encoded, and don't re-encode in that case.
Fixes #687
> fix(util): Don't double-encode percent-encoded URIs

- .coveragerc
- .gitignore
- setup.cfg
- tools/test-requires
- tox.ini
Use pytest instead of nose since it has a better ecosystem and will
allow us to write pytest-style tests in the future.
> chore(tox): Switch test runner from nose to pytest

- falcon/testing/client.py
- falcon/testing/helpers.py
- falcon/util/misc.py
- tests/test_utils.py
As an alternative to specifying a raw query string, also allow for specifying parameters as a dict.
> feat(testing): Specify query parameters as a dict in simulate_request()

- tools/build.sh
Don't build binary wheels for Darwin (OS X) since it isn't really
necessary to have cythonized code in a development environment, and
using the pyenv-installed Pythons results in compatibility issues
that just aren't worth it in any case.
> chore: Remove portion of build.sh that deals with binary Darwin wheels

- falcon/testing/client.py
A developer wishing to test high-performance file transmission may wish
to pass a mock for wsgi.file_wrapper to simulate_get(). This kwarg is
not documented for other simulate_*() functions since they are unlikely
to use it.
> doc(testing.client): Document file_wrapper kwarg for simulate_get

- falcon/cmd/print_routes.py
- setup.py
- tests/test_cmd_print_api.py
While doing some documentation work I realized it would be nice to have a quick script that dumps out route information and wrote this. I think it may be helpful for other folks as well.
> chore(adds print-api-routes): new utility to print routes

- docs/api/util.rst
- falcon/__init__.py
- falcon/util/__init__.py
Previously "from falcon import uri" worked but "import falcon.uri" did
not. TimezoneGMT is already available from the front-door falcon
module, but the documentation referenced falcon.util.TimezoneGTM.
Fix this up and update the docs to suit.
> feat(util): Make it easier to reference uri module and TimezoneGMT class

- falcon/api.py
- falcon/api_helpers.py
- falcon/http_error.py
- falcon/request.py
- falcon/request_helpers.py
- falcon/util/misc.py
- falcon/util/time.py
- falcon/util/uri.py
In a google-style docstring, this is problematic:
Returns:
str: Some really long description that requires more
than one line
Since the additional text (i.e., "than one line") is indented,
napolean gets confused and incorrectly formats the description. The
fix is to align subsequent lines with the first:
Returns:
str: Some really long description that requires more
than one line.
Along the way I also added missing return types as needed.
> doc: Unindent additional Return lines to work around napolean bug

- docs/api/middleware.rst
- falcon/api.py
- falcon/api_helpers.py
- tests/test_middleware.py
Pass a flag to process_request() to indicate whether or not the request
succeeded (i.e., no exceptions were raised by other middleware methods
hooks, responders, etc.)
Closes #606
> feat(middleware): Pass a request status flag to process_request()

- docker/Makefile
- docker/bench_py27_pip.Dockerfile
- docker/bench_py35_pip.Dockerfile
- docker/bench_pypy2_pip.Dockerfile
- docker/benchmark.sh
The dockerfiles used to build the ``falconry/falcon-bench`` images on Docker Hub
> (chore) Adding dockerfiles for falcon-bench

- falcon/responders.py
Fixes this issue: https://github.com/falconry/falcon/issues/895
405 errors are never passed to registered error handlers, because the na-responder does not raise an exception, but modifies the response directly.
> Raise HTTPMethodNotAllowed instead of modifying response directly

- docs/api/routing.rst
- falcon/api.py
- falcon/request.py
- falcon/routing/compiled.py
- tests/test_custom_router.py
- tests/test_default_router.py
This has been requested by several members of the community who would
like a way to access the URI template in middleware, etc. (e.g., for
logging).
Fixes #619
> feat(Request): Expose the URI template that was matched for the request

- falcon/api.py
- falcon/request.py
- falcon/request_helpers.py
- falcon/testing/base.py
- falcon/testing/resource.py
- tests/conftest.py
- tests/test_query_params.py
- tests/test_request_body.py
- tests/test_wsgi.py
- tests/test_wsgi_interface.py
* Add a new bounded_stream property that can be used for more
predictable behavior vs. stream, albeit with a slight performance
overhead (the app developer is free to decide whether or not to
use it).
* Only automatically consume the incoming stream on POST requests,
since that is the only time form-encoded params should be included
in the body (vs. the query string). This guards against unexpected
side-effects caused by misbehaving or even malicious clients.
* Check Content-Length to ensure a body is expected, before attempting
to parse form-encoded POSTs. Also pass the Content-Length to
stream.read as an extra safety measure to guard against differences
in WSGI input read() behavior.
* Improve the documentation surrounding all of these behaviors.
Fixes #407
> fix(Request): Improve various related aspects of stream handling

- .travis.yml
- docs/api/testing.rst
- falcon/request_helpers.py
- falcon/testing/client.py
- tests/test_access_route.py
- tests/test_before_hooks.py
- tests/test_boundedstream.py
- tests/test_cookies.py
- tox.ini
* Migrate additional test modules away from the deprecated framework,
taking care to demonstrate both unittest- and pytest-style testing.
* Add an additional Cookie class and parse cookies in the Result object
to facilitate cookie testing.
* Extend BoundStream to implement more of the IO protocol so that
it works with mock WSGI input objects (and potentially improves
compatibility as a drop-in replacement for the native WSGI input
object).
* Disable pypy3 testing on Travis, since it uses a buggy cookie impl,
and also we don't support pypy3 (yet) since overall it isn't fully
baked.
* Specify latest pypy version for Travis testing, which has improved
cookie handling.
> test: Migrate several test modules away from the deprecated framework

- tox.ini
Sometimes sphinx doesn't detect that a module has changed and needs
to be re-autodoc'd. Work around this by just forcing sphinx to
read everything each time.
Also bump up the number of workers to speed things along (reduces the
build time to 8 sec vs. 11 sec. on my MBP).
> chore(docs): Work around sphinx not always detecting modified *.py

- docs/ext/rfc.py
- falcon/response.py
Correct outdated information in the set_cookie() docstring, as well
as expound on certain key points and provide references to relevant
sections of RFC 6265.
> doc(Request): Expand and correct documentation for set_cookie()

- docs/api/util.rst
- falcon/__init__.py
- falcon/uri.py
- tox.ini
The previous attempt at fixing this failed, and so do something a bit more evil. We'll remove this later in 2.0 once util goes away and everything is just implemented under the falcon package directly.
> fix(util): Fix falcon.uri import

- falcon/util/uri.py
Most of the time the token will be found in the dict, so let's optimize
for that and avoid an extra membership check (if token in _HEX_TO_BYTE).
> perf(uri): Replace if...else with try...except in the decode function

- falcon/api.py
- falcon/api_helpers.py
- falcon/hooks.py
- falcon/util/misc.py
inspect.getargspec() is deprecated under py3k, and among other things
does not work for annotated functions. Use inspect.signature instead.
Fixes #911
> fix: Use inspect.signature on py3k instead of inspect.getargspec

- falcon/testing/helpers.py
- tests/test_req_vars.py
- tox.ini
When a request comes in, web servers decode the path. The decoded path
may contain UTF-8 characters,  But according to the WSGI spec, no
strings can contain chars outside ISO-8859-1. Therefore, to reconcile
the URI encoding standard that allows UTF-8 with the WSGI spec that does
not, WSGI servers tunnel the string via ISO-8859-1.
falcon.testing.create_environ() needs to mimics this behavior, e.g.:
```py
tunnelled_path = path.encode('utf-8').decode('iso-8859-1')
```
falcon.Request already does the following to reverse the process:
```py
path = tunnelled_path.encode('iso-8859-1').decode('utf-8', 'replace')
```
Fixes #817
> fix(testing): Modify create_environ() to tunnel Unicode chars

- falcon/errors.py
- setup.py
- tests/test_error.py
The changes should cause no breaks, however as I ran the tests some of the tests failed, but the problem was with the Wrapper and some module imports
> (refactor) Make the title and description optional for most error classes

- .gitignore
- setup.cfg
- setup.py
See also: http://docs.pytest.org/en/latest/goodpractices.html?highlight=setup#integrating-with-setuptools-python-setup-py-test-pytest-runner
> chore: Use pytest runner instead of nose collector for "setup.py test"

- falcon/response.py
- falcon/response_helpers.py
- tests/test_headers.py
This issue was partially addressed by #490. In this patch, also
ensure that header property setters are converting to str. Also
optimize the logic by inlining it and using str() instead of
str.encode().
Also update docstrings to reference "US-ASCII" instead of
"ISO-8559-1". The latter is technically what is specified in the
WSGI spec, but the HTTP RFCs restrict header text to "US-ASCII" so
there is no reason to expect/allow additional characters.
Fixes #413
> fix(Response): Convert header values to str if needed

- docs/api/errors.rst
- falcon/api.py
- falcon/http_error.py
The set_error_serializer() example should demonstrate setting the
'Vary' header, since the response does vary depending on the
'Accept' header in the request.
Also, cross-link set_error_serializer() from the errors page.
> doc(API): Set 'Vary' header in set_error_serializer example, cross-link

- falcon/request.py
json.load(req.stream) -> json.load(req.bounded_stream)
> doc(API): Fixing typo in json request loading example

- falcon/testing/client.py
Currently, ' foo=bar' is parsed as ' foo' being the cookie_name in the tests.
> fix: strip whitespaces when parsing cookie in tests

- setup.py
pytest-runner is not needed unless doing python setup.py test. Thus it's better to move it to the right place.
This patch is not tested yet. Because I'm trying to build falcon for a old CentOS 6 system. Please consider this change.
> Move pytest-runner to tests_requires

- .coveragerc
- .travis.yml
- CONTRIBUTING.md
- tox.ini
Do the following:
* Use python 3.5 in lieu of 3.4 as the "default" py3k version.
* Explicitly set basepython for all environments so the right
version is used outside of travis.
* Show missing lines when test coverage fails
* Add ujson test environments to check
> chore: Update test environments

- falcon/request.py
- tests/test_options.py
- tests/test_req_vars.py
Option strip_url_path_trailing_slash allows keeping a trailing slash, if
exists, at the end of the request url path when normalizing it.
The default conforms to the previous behavior, in which such a trailing
slash is stripped, in order to avoid introducing any breaking changes.
> feat(Request): Add an option to keep a trailing slash in the request path (#966)

- falcon/request.py
- tests/test_req_vars.py
See also PR #917
This patch does the following:
* Moves the docstring for the deprecated "protocol" alias to be
below the new, recommended "scheme" attribute.
* Changes the type of "port" to an int to be consistent with the
parse_host() utility function.
* Expand the "port" docstring.
* Add a docstring for "netloc".
* Implement "uri" in terms of "netloc".
* Handle default port in the try block, since that it is not
necessary to do so in the case that SERVER_PORT is used.
* In the tests, inherit from TestCase instead of the deprecated
TestBase class.
* DRY up the tests.
* Test the new attributes with both the HTTP/1.0 and HTTP/1.1
protocols.
> feat(Request): Refine the new protocol, port, and netloc attrs

- docs/_static/custom.css
- docs/conf.py
When the sidebar is too tall for the browser window, the user can
not scroll down to view the bottom of the sidebar when it is fixed.
Fixes #970
> doc: Don't use a fixed sidebar to better accomodate small screens

- falcon/api.py
- tests/test_httpstatus.py
While not specified in the spec that the status must be of type str
(not unicode on Py27), some WSGI servers can complain when it is not.
> fix(API): Normalize response status to type str under py27

- falcon/routing/compiled.py
Many people are confused by the terse error message that "The URI
template for this route conflicts with another route's template."
Expand this message to provide an example of what typically causes
this conflict, and how to remedy it.
> fix(CompiledRouter): Provide a detailed error message for route conflicts

- docs/_static/custom.css
- docs/api/request_and_response.rst
- falcon/request.py
- falcon/response.py
* Use "Keyword Args" to be more consistent with docstrings in other
modules.
* Use the full names of the Request and Response classes in the
title of the page.
* Adjust CSS to improve spacing and refine the way types and citations
are displayed.
> doc(Request,Response): Improve presentation

- docs/api/api.rst
- docs/api/cookies.rst
- falcon/__init__.py
- falcon/api.py
- falcon/request.py
- falcon/response.py
- tests/test_cookies.py
This should be a more practical approach vs. having to pass it every time to `set_cookie()`.
> feat(Response): Add an option for disabling secure cookies for testing

- docs/api/routing.rst
- falcon/api.py
- falcon/util/misc.py
- tests/test_custom_router.py
This change allows the `find` method of a custom router to accept a `req` keyword argument to which a request instance is passed.
> feat(API): add support for routing on full request

- falcon/testing/resource.py
- tests/test_default_router.py
- tests/test_uri_templates.py
- tox.ini
Note that some tests were moved from test_uri_templates to test_default_router.
> test: Migrate URI template and router testing to pytest

- falcon/api.py
- falcon/routing/compiled.py
- tests/test_default_router.py
Fix the following bugs:
* Only the '.' special character is properly handled, even though
some URL schemas, such as OData, make use of other characters,
like parens.
* Using duplicate field names leads to a nasty re error being
raised in the case of them being contained to the same
node, and a silent overwriting of param values in the case of
field values being duplicated across multiple nodes.
> fix: URI template field parsing bugs

- .travis.yml
- falcon/response.py
- tests/test_headers.py
This PR adds a single method, `delete_header`, to `Response`.
Previously, `Response` had methods to get and set headers, but no way to delete them, once set. We came across a need to delete response headers that had been set upstream, and without a `delete_header` method we've had to resort to directly manipulating `Response._headers`. This PR alleviates that abstraction-violation.
Tox tests all pass, but this is my first Falcon PR so please let me know if I've missed anything and I'll gladly fix.
> Response header delete

- falcon/routing/compiled.py
- tests/test_custom_router.py
- tests/test_default_router.py
Rather than compiling the routing tree directly to Python code, first generate an AST and then use it to produce the code. This provides several benefits, including:
* It makes the compilation process easier to reason about.
* It makes it easier to keep track of indentation and whitespace.
* It sets us up for being able to make transformations that we will need to do to support URI template filters, etc. in the future.
> feat(CompiledRouter): Add an intermediate AST step to the compiler

- docs/api/index.rst
- docs/api/media.rst
- falcon/api.py
- falcon/media/__init__.py
- falcon/media/base.py
- falcon/media/handlers.py
- falcon/media/json.py
- falcon/media/msgpack.py
- falcon/media/validators/jsonschema.py
- falcon/media_handlers.py
- falcon/request.py
- falcon/response.py
- requirements/tests
- tests/test_media_handlers.py
- tests/test_request_media.py
- tests/test_response_media.py
- tests/test_validators.py
This is a first pass at a non-breaking change that'll allow for a customizable media handling system. This approach combines many of the suggestions brought up by the community in #145.  
One the thing that is left out of this PR is handling full content negotiation (i.e. connecting the request's accept header to the response's content-type). Unfortunately, this is a harder problem to solve in a backwards compatible fashion that doesn't affect performance. However, especially as we move towards v2, I think that would be a great opportunity to revist full negotiation. In the meantime, there are several easy workarounds for people needing this functionality.
> Request and Response media-type handling

- falcon/request.py
- tests/test_query_params.py
> Added a get_param_as_datetime() method to fetch query param as datetime

- falcon/errors.py
> docs(errors): Removing extra "headers" entries from error docstrings

- falcon/errors.py
The bracketed convention does not work with our sphinx setup, so switch to a format that *will* be recognized and linked.
> doc(errors): Fix RFC links

- falcon/routing/converters.py
- tests/test_uri_converters.py
Also rename "fragment" to "value" to be consistent with the terminology used in the docstrings.
TODO: In a followup PR, reference the converter classes in the docs.
> feat(routing): Add ABC for URI template field converters

- falcon/request.py
- falcon/response.py
Reorder attributes in the docstring to be more intuitive. Also edit the docstring for Response.body for clarity.
> doc(Request/Response): Reorder attributes in the docstring

- falcon/testing/client.py
This allows us to customize any requests by just extending
TestClient and overriding `simulate_request`
Here's an example use case:
I want to inject a custom header to all my requests.  To do that currently, 
I have to pass in a headers keyword argument to every `simulate_*` method call.
With this change, I can do this:
```
class CustomClient(TestClient):
def simulate_request(self, *args, **kwargs):
original_headers = kwargs.get('headers', {})
kwargs['headers'] = original_headers.update({'CustomHeader': 'CustomValue'}
return super().simulate_request(self, *args, **kwargs)
```
> update TestClient methods to use simulate_request

- docs/api/errors.rst
- tests/test_wsgi_interface.py
Use double quotes for strings, since there is a single apostrophe
inside.
> docs(api/errors): fix syntax error in example code

- falcon/hooks.py
- falcon/util/misc.py
- tests/test_after_hooks.py
- tests/test_before_hooks.py
The framework always passes extra args as keyword arguments. However, when an app calls a responder directly, it might use positional arguments instead, so we need to handle that case. This might happen, for example, when overriding a resource and calling a responder via super() in order to introduce a new version of the resource side-by-side.
> fix(hooks): Allow passing extra args positionally.

- .coveragerc
- .travis.yml
- requirements/tests
- tools/mintest.sh
- tools/testing/combine_coverage.sh
- tox.ini
Generate unique coverage filenames for each env to ensure they don't step on eachother when multiple tox jobs run in parallel.
> chore: Fix code coverage race condition

- tests/test_utils.py
In doing some test coverage testing locally, I discovered that somehow we neglected to cover these functions when TestClient was last modified. With this change, my local coverage results now show 100%.
> test: Cover testing.simulate_* free functions

- falcon/testing/client.py
The TestClient docstring suggests subclassing TestClient to override
simulate_request(), but this does not work as intended since the other
simulate_*() methods don't actually call self.simulate_request(). Modify
those methods to do so.
Fixes #1149
> fix(TestClient): Change TestClient to call self.simulate_request()

- falcon/testing/client.py
- tests/test_utils.py
Instead of raising an error, return None. This simplifies testing and avoids the element of surprise.
> fix(TestClient): Return None from the json property when there is no content in the response.

- .gitignore
- falcon/response.py
- falcon/response_helpers.py
- tests/test_headers.py
- tests/test_response_media.py
When setting a non-str value for a header, it can be suprising to
users when it isn't converted to a string automatically under Python 3.
> fix(Response): Always convert header values to str if necessary

- falcon/forwarded.py
- falcon/request.py
- tests/test_request_forwarded.py
- tests/test_utils.py
I have implemented a fix for issue #1116. 
In the case of the malformed forwarded header I decided to just say the whole forwarded is malformed and set it to None.
> fix(Request): Properly handle quoted strings in forwarded header

- docs/api/hooks.rst
- docs/api/middleware.rst
Added tips on the middleware and hooks docs to explain how to pass data from a middleware / hook function to a resource addressing #1240
> doc: Tips on passing data from middleware/hooks to resources (#1240)

- pip.conf
- tox.ini
This should resolve issues where people who have corporate devpi default
configuration have difficulty pulling requirements on build.
> chore(build): Force set a pip config to use PyPI

- docs/api/routing.rst
- falcon/api.py
- falcon/routing/compiled.py
- tests/test_custom_router.py
BREAKING CHANGE: 
Routers were previously allowed to accept additional args and
keyword arguments, and were not required to use the variadic form. Now,
they are only allowed to accept additional options as variadic keyword
arguments, and to ignore any arguments they don't support. This helps
overridden router logic be less fragile in terms of their interface
contracts, which also makes it easier to keep Falcon backwards-compatible
in the face of any future changes in this area.
BREAKING CHANGE: 
API.add_route() previously accepted *args, but no longer does.
Additionaly, suffix is now specified as an explicit keyword argument. This
means that if a single additional non-keyword argument was previously
passed, it will now erroneously be assigned to the suffix arg. This should
be a simple …
> refactor(routing): Require custom routers to accept extra options only via **kwargs

- setup.cfg
- tests/test_query_params.py
pytest fails when overlapping paths are passed to it and when using parametrized classes. Remove overlapping paths in the configuration and also refactor to use parametrized fixtures instead.
> test: Work around pytest bug

- falcon/media/base.py
- falcon/media/json.py
- falcon/media/msgpack.py
- falcon/request.py
- falcon/request_helpers.py
- falcon/response.py
- tests/test_request_media.py
#1312 
Providing of real content-type to media handlers for deserializing and serializing media by corresponding to real content-type or specific parameters (such as "boundary" for multipart/form-data). Also provided content-length for special cases.
For avoiding reading big data to memory to media handlers now providing bounded stream instead raw data. Also consumption of stream proceed by small chunks.
> Providing of real content-type to media handlers.

- falcon/routing/static.py
- tests/test_static.py
Co-authored-by: snobu <foo@snobu.org>
Co-authored-by: Ben Demaree <bendemaree@gmail.com>
Co-authored-by: Nick Zaccardi <nicholas.zaccardi@gmail.com>
> fix(routing): assign Content-Type when serving static fallback files

- falcon/response.py
- falcon/routing/compiled.py
- falcon/routing/util.py
- setup.py
- tests/test_sinks.py
- tox.ini
``W504`` **is** actually among the warnings ignored by default even by the new Flake8 version (3.6.0), however by specifying our ``--ignore`` in ``tox.ini`` we seem to override the default ignore list, a breaking change in behaviour I am quite sure.
``W605`` seems a fair thing to warn on, although it could be perceived as somewhat harsh in the docstring context. But with the proposed changeset we should thereby comply.
> style: ignore Flake8 warning W504 and address W605 violations

- falcon/testing/client.py
- tests/test_py2_wsgi.py
> Convert TestClient Header Values to `str` in Py2

- falcon/request.py
- tests/test_query_params.py
#1387 
@vytas7 @kgriffs In the first commit, I removed unnecessary parentheses. Also would be cool, if you have some additional places where we need to rename(arguments and etc.) let me know.
> style: avoid builtins python names

- falcon/util/compat.py
- falcon/util/structures.py
Update the import path for [abstract base classes](https://docs.python.org/3/library/collections.abc.html), which changed from `collections` to `collections.abc` in Python 3.3.
This resolves warnings like this:
```
.../site-packages/falcon/util/structures.py:35: DeprecationWarning:
Using or importing the ABCs from 'collections' instead of from
'collections.abc' is deprecated, and in 3.8 it will stop working
class CaseInsensitiveDict(collections.MutableMapping):  # pragma: no cover
```
> refactor: Import abstract base classes from collections.abc under Python 3

- CHANGES.rst
- README.rst
- docs/api/hooks.rst
- docs/api/middleware.rst
- docs/changes/2.0.0.rst
- docs/user/faq.rst
- docs/user/quickstart.rst
- falcon/bench/queues/api.py
- falcon/request.py
- falcon/response.py
- tests/test_example.py
- tests/test_request_context.py
- tests/test_response_context.py
- tools/mintest.sh
ref https://github.com/falconry/falcon/issues/1120
Work in progress:
> feat(request, response): change context type to a subclass of dict

- .coveragerc
- .travis.yml
- CHANGES.rst
- README.rst
- docs/changes/2.0.0.rst
- docs/index.rst
- docs/user/install.rst
- docs/user/intro.rst
- falcon/media/handlers.py
- falcon/request.py
- falcon/vendor/mimeparse/LICENSE
- falcon/vendor/mimeparse/__init__.py
- falcon/vendor/mimeparse/mimeparse.py
- setup.py
- tools/check-vendored.sh
- tox.ini
> chore: Vendor python-mimeparse

- docs/_static/custom.css
Closes #1323 
I checked several different pages, and for anything that doesn't overflow it looks good. Since I changed the color just slightly so `self` was more readable here's a screenshot.
We have some overflow in the current docs, just based on our source line length and what the current docs css can handle. May want to create a new ticket for fixing overflow.
See:
> docs(style): block highlighting

- falcon/media/validators/jsonschema.py
the usage of `@jsonschema.validate` on methods loses the doc-string
when using sphinx to create documents.
`@wraps` will preserve the doc-string
issue #1431
> fix(sphinx): add wraps in jsonschema.validate decorator

- .travis.yml
- CHANGES.rst
- docs/changes/2.0.0.rst
- falcon/api.py
- falcon/response.py
- tests/test_hello.py
- tests/test_response.py
This patch "removes" the deprecated stream_len property, fully replacing it's use by the content-length property/header. Along the way, the way API uses content-length (in lieu of stream_len) was optimized.
> refactor(Response): Remove stream_len property

- CHANGES.rst
- docs/changes/2.0.0.rst
References closed issue, #1276 
Something went screwy with my old branch for this PR, sorry to recreate a new one.
- Updated terminology to use 'kwarg'
- Updated 2.0.0rst, although not sure why the syntax style is a little different between changes.rst and 2.0.0rst, tried to stay consistent
> docs(changes) independent middleware

- CHANGES.rst
- docs/changes/2.0.0.rst
- falcon/request.py
- tests/test_before_hooks.py
- tests/test_example.py
- tests/test_utils.py
- tests/test_wsgi.py
- tests/test_wsgiref_inputwrapper_with_size.py
BREAKING CHANGE: Now that we have Request.bounded_stream, it is no longer
necessary to wrap wsgiref's stream to avoid hangs. In fact, we've been
warning in the docs about unexpected behavior like this for quite some
time, so not many app developers should be relying on our automatic wrapping
at this point.
> cleanup(Request): Remove automatic wrapping of Request.stream

- .travis.yml
- CHANGES.rst
- CONTRIBUTING.md
- docker/Makefile
- docker/bench_py27_cython.Dockerfile
- docker/bench_py37.Dockerfile
- docker/bench_py37_cython.Dockerfile
- docs/changes/2.0.0.rst
- setup.py
- tools/mintest.sh
- tox.ini
Addresses https://github.com/falconry/falcon/issues/1405
For the reference: I am leaving Hug tests at CPython 3.6, it seems that Hug's pinned build requirements fail to install under 3.7.
Filed as: https://github.com/timothycrosley/hug/issues/725
> chore: add official support for CPython 3.7

- CHANGES.rst
- docs/api/cookies.rst
- docs/changes/2.0.0.rst
- falcon/request.py
Rather than trying to protect app developers from themselves, error on the
side of performance and return direct references to the cookies and headers
dictionaries once they are constructed and cached.
> perf(request): Return direct reference to parsed cookies, headers objects

- CHANGES.rst
- docs/api/cookies.rst
- docs/changes/2.0.0.rst
- falcon/errors.py
- falcon/response.py
- tests/test_headers.py
Previously, setting raw cookies was not supported without having to subclass Response and override several methods. This patch adds official support for this functionality, while also explicitly disallowing the use of Set-Cookie with certain generic header manipulation methods that have semantics that are incompatible with Set-Cookie.
Fixes #1265
> feat: Provide a way to set raw cookie headers

- falcon/api.py
- falcon/api_helpers.py
- falcon/http_error.py
- tests/test_httperror.py
Addresses https://github.com/falconry/falcon/issues/1422
This is still somewhat work in progress, I am sharing this to speed things up for the impending 2.0 release.
If the general direction looks good, I will update `CHANGES.rst` etc.
> fix(errors): call custom serializers even for errors without represention

- falcon/cmd/print_routes.py
- tests/test_cmd_print_api.py
- tests/test_cython.py
Closes #1400 
(see the issue for problem background and discussion).
Note that the solution is somewhat counter-intuitive and strange: removing `test/__init__.py`. This prevents `pytest` from treating `tests` as a module which in turns makes `pytest` change directory to its parent, at the same time shadowing cythonized Falcon with the local source.
Could this removal be a problem?
> fix(cython): properly test cythonized Falcon & make print_routes work with cythonized responders

- CHANGES.rst
- docs/api/cookies.rst
- docs/changes/2.0.0.rst
- falcon/request.py
- falcon/request_helpers.py
- tests/test_cookies.py
This patch provides support for getting all values for a given cookie (when
the same cookie is included multiple times in the request), and also optimizes
request cookie parsing to make it an order of magnitude faster.
BREAKING CHANGE: Request.cookies now gives precedence to the first value
encountered in the Cookie header for a given cookie name, rather than the
last.
BREAKING CHANGE: Request cookie parsing no longer uses the standard library
for most of the parsing logic. This may lead to subtley different results
for archaic cookie header formats, since the new implementation is based on
the latest RFC 6265.
Closes #1107
Closes #1046
> feat(Request): Improve request cookie handling

- falcon/testing/helpers.py
- falcon/util/uri.py
- tests/test_utils.py
When testing using a URL that contains a "+" in the path component (as distinct from the query component), Falcon replaces "+" with a space—this does not appear to be appropriate behavior.
Consider the call
```python
import falcon.testing
client = falcon.testing.TestClient(app)
client.simulate_get("/a+b")
```
for some `app`. This code initiates the sequence of method invocations:
1. `falcon.testing.client.TestClient.simulate_get()`
2. `falcon.testing.client.TestClient.simulate_request()`
3. `falcon.testing.client.simulate_request()`
4. `falcon.testing.helpers.create_environ()`
5. `falcon.util.uri.decode()`
The last method replaces "+" with a space so that the path `/a+b` becomes `/a b`.
As I understand it, plus signs should be unquoted in query strings but not in the path component of a …
> Testing framework preserves + in URL paths

- docs/api/util.rst
- falcon/request.py
- falcon/request_helpers.py
- falcon/util/__init__.py
- falcon/util/structures.py
- tests/test_request_attrs.py
- tests/test_utils.py
Closes #1211
`W/` prefix was simply ignored as proposed in the issue by @kgriffs.
> refactor(falcon.request): Change etag headers to return a list of ETag

- .travis.yml
- falcon/response.py
- tests/test_headers.py
- tests/test_response.py
Restore the stream_len alias since it was only deprecated as of 2.0, not 1.4, and we should allow at least one release cycle before removing deprecated parts of the interface.
> refactor(Response): Restore the stream_len alias

- CHANGES.rst
- docs/changes/2.0.0.rst
This patch also moves the "Changes to Supported Features" section up so that
it is more prominent, since we don't want people to miss the fact that we
will be dropping Python 2 support completely in the next major release.
> doc(CHANGES): Note the removal of the charset parameter for the JSON media type

- CHANGES.rst
- docs/changes/3.0.0.rst
- falcon/response.py
Now that we no longer support Python 2, there is no reason to coerce
variables to a str in certain cases that are cleaned up by this patch.
BREAKING CHANGE: Although in practice this patch should not break any
apps, it is technically a breaking change in the case that an
app was passing a non-string value for the header name.
> perf(Response): Remove unnecessary coercion to str

- CHANGES.rst
- docs/changes/3.0.0.rst
- falcon/response.py
- tests/test_headers.py
- tests/test_response.py
This appears to be the only existing functionality marked as deprecated hanging out in the code base. (Part of #1029.)
> refactor(Response): Remove deprecated `stream_len` property

- docs/api/routing.rst
- falcon/constants.py
- falcon/routing/util.py
- tests/test_http_custom_method_routing.py
Making sure we're strip and uppercase the custom methods specified from the environmental variable. Also, rewording docs a touch, and expanding the tests.
> fix(custom-http-methods): Making sure we clean up the env var input string

- docs/api/hooks.rst
- docs/api/redirects.rst
Do so to stop Sphinx 2.1+ from complaining about duplicate object description of `falcon`.
> chore(Sphinx): explicitly specify autodoc directives for hook functions and redirect exceptions

- docker/bench_py37.Dockerfile
- docker/bench_py37_cython.Dockerfile
- docker/bench_pypy3.Dockerfile
the maximum version is no longer necessary
because only recent Python 3.x versions are beeing tested
closes #1582
Removed "<2" restrictions in all Dockerfiles.
N/A
> chore(dockerfiles): remove "<2" from django dependency

- falcon/http_error.py
- falcon/http_status.py
The ordering of the class docstring sections for HTTPError and HTTPStatus was changed in this patch to be consistent with other class docstrings in the codebase.
N/A
> docs(HTTPError,HTTPStatus)): Fix ordering of docstring sections

- examples/look/requirements/test
In https://github.com/falconry/falcon/pull/1611, we were unable to use the latest Gunicorn due to how the `look` tutorial was specifying app in the command line.
The latest Gunicorn release seems to address the issue (https://github.com/benoitc/gunicorn/issues/2175), so we no longer need to pin an old Gunicorn version.
> chore(tutorial): unpin Gunicorn in the `look` test requirements

- falcon/constants.py
- falcon/testing/client.py
- setup.cfg
- tests/test_http_custom_method_routing.py
- tests/test_http_method_routing.py
- tests/test_httperror.py
This patch cleans up the less-than-useful warnings that are typically reported by pytest runs whenever there are any test failures. Along the way, I discovered that the `WEBDAV_METHODS` list was missing a comma.
> test: Clean up pytest warnings and fix missing comma in WEBDAV_METHODS

- .travis.yml
Fix our coverage CI gate by removing the unused `coveralls` dependency which was pulling in older `codecov`, which was in turn conflicting with the newest one installed into `tox` environments.
This is probably preferred to just pinning coverage to an older version, as attempted in https://github.com/falconry/falcon/pull/1622.
> chore(Travis): do not install (unused) coveralls

- docs/_newsfragments/1603-smart-exception-handler-precedence.feature.rst
- falcon/app.py
- tests/test_error_handlers.py
Rather than selecting error handlers in LIFO order of registration, select the error handler corresponding to the nearest direct ancestor of the exception type raised. So, for example, if an app only adds a custom error handler for the Python ``Exception`` class, and an ``HTTPForbidden`` error is raised, then we use the default handler for ``HTTPError`` rather than the more general ``Exception`` handler (which is the pre-existing behavior). 
This is implemented by storing error handlers on the API object as a dict rather than a list and looking them up using the method resolution order attribute (`__mro__`) on the raised exception class. 
~~This commit only includes the actual implementation and does not address testing or documentation. I am seeking implementation feedback before …
> feat(API): on exception, select most specific error handler available

- tests/test_app_initializers.py
Added tests for `falcon.API`, `falcon.App` initializers, which check whether a `media_type` is overriding.
https://github.com/falconry/falcon/issues/1577
> test: Added tests, which check whether App/API initializers are overriding

- MANIFEST.in
- docs/_newsfragments/1630-set-response.feature.rst
- falcon/response.py
- tests/test_headers.py
Changed behavior in `Response.set_headers()` the method, now we're checking for interface compliance, instead of check whether an object is an instance of ``dict``.
Also, new changes allow passing a custom class which will be setting headers for a response.
e.g
```python
class CustomHeaders:
def items(self):
return [('header', 'value')]  # or return {'header': 'value'}
class Resource:
def on_get(self, req, resp):
custom_headers = CustomHeaders()
resp.set_headers(custom_headers)
```
https://github.com/falconry/falcon/issues/1546
This is just a reminder about the most common mistakes.  Please make sure that you tick all *appropriate* boxes.  But please read our [contribution guide](https://github.com/falconry/falcon/blob/master/CONTRIBUTING.md) at least once; it will save you a few review …
> Rewrites behaviour of Response.set_headers() method

- docs/_newsfragments/default-404-responder-specialized-error.feature.rst
- docs/api/errors.rst
- docs/api/routing.rst
- docs/user/faq.rst
- falcon/app.py
- falcon/errors.py
- falcon/responders.py
- tests/test_error_handlers.py
When no route matches a request, raise a subclass of HTTPNotFound so that
a custom error handler can distinguish that specific case if desired.
(This was inspired by a recent chat with a user in the community.)
> feat(responders): Raise a specialized subclass of HTTPNotFound

- docs/_newsfragments/simulate-request-content-type.feature.rst
- falcon/testing/client.py
- tests/test_app_initializers.py
- tests/test_testing.py
It is often the case that the only reason to pass the headers kwarg to
simulate_request() is to set the content type. This patch adds a
convenience kwarg for this use case.
N/A
> feat(testing): Accept a content_type kwarg when simulating requests

- docs/api/index.rst
- docs/index.rst
This patch groups the guide sections together in the nav sidebar. It also renames the "Classes and Functions" setting to "Framework Reference" because it contains additional feature docs for media, middleware, etc.
> doc: Group guides in sidebar nav, and rename "Classes and Functions" section

- docs/_static/custom.css
- docs/api/app.rst
- docs/api/cookies.rst
- docs/api/errors.rst
- docs/api/middleware.rst
- docs/api/routing.rst
- docs/user/tutorial.rst
- falcon/app.py
- falcon/asgi/app.py
- falcon/request.py
- falcon/response.py
- falcon/routing/compiled.py
- tests/test_error_handlers.py
This patch is a bit of a grab bag of items that I noticed and
fixed while starting work on fleshing out the docs for the new ASGI
implementation.
Note that there is still quite a bit of work to do in order to integrate
ASGI into the docs. Many docs need to be combed and updated to work with
ASGI and WSGI side-by-side, and there are still plenty of missing docs for
the new ASGI classes and functions.
> doc/refactor(asgi): Start fleshing out docstrings, tweak doc refs, remove add_error_handler shimming

- docs/api/util.rst
- falcon/app_helpers.py
- falcon/asgi/app.py
- falcon/asgi/response.py
- falcon/hooks.py
- falcon/media/validators/jsonschema.py
- falcon/routing/compiled.py
- falcon/testing/client.py
- falcon/util/misc.py
- setup.py
- tests/asgi/_asgi_test_app.py
- tests/asgi/_cythonized.pyx
- tests/asgi/test_cythonized_asgi.py
- tests/asgi/test_scheduled_callbacks.py
- tests/test_after_hooks.py
- tests/test_before_hooks.py
- tests/test_middleware.py
- tox.ini
This patch provides workarounds for the fact that cythonized coroutine functions
can not be detected.
In several places in the framework, we rely on being able to introspect a passed
callable in order to determine how to wrap it or call it later. As a workaround,
this patch gives the caller a way to explicitly indicate that the framework may
assume a coroutine function.
Also, we relax our type checking so that we don't raise an error on Cython
functions; the app developer will simply have to be trusted to pass the correct
type of function if they are using Cython.
This is just a reminder about the most common mistakes.  Please make sure that you tick all *appropriate* boxes.  But please read our [contribution guide](https://github.com/falconry/falcon/blob/master/CONTRIBUTING.md) at least …
> fix(asgi): Errors caused by not being able to detect cythonized coroutine functions

- docs/_static/custom.css
Fix the paragraphs in attr descriptions running together.
N/A
> docs: Fix no blank line after initial paragraph in attr description

- docs/_newsfragments/1656-tests-on-windows.misc.rst
- falcon/response.py
- falcon/routing/static.py
- tests/asgi/_asgi_test_app.py
- tests/asgi/test_asgi_servers.py
- tests/asgi/test_boundedstream_asgi.py
- tests/conftest.py
- tests/test_cmd_print_api.py
- tests/test_response.py
- tests/test_static.py
Make the test work on windows. This mainly involves changes to the `tests` files.
The serve static constructor has been updated to use `os.path.normpath` on the `directory` and the `fallback_filename`
I've also created ids for pytest fixtures so that the logging is a bit more readable, in particular to the fixtures that tests long strings and the `asgi` fixture so that the tests read `[asgi]` and `[wsgi]` instead of true/false (maybe async/sync is better?)
Closes #1656 
If an item doesn't apply to your pull request, …
> Fix tests on windows

- docs/api/cookies.rst
- docs/api/middleware.rst
- docs/api/request_and_response.rst
- docs/api/request_and_response_asgi.rst
- docs/api/request_and_response_wsgi.rst
- docs/api/routing.rst
- docs/api/status.rst
- docs/api/util.rst
- docs/changes/1.0.0.rst
- docs/changes/1.3.0.rst
- docs/changes/1.4.0.rst
- docs/changes/2.0.0.rst
- docs/user/faq.rst
- docs/user/tutorial.rst
- falcon/asgi/request.py
- falcon/asgi/response.py
- falcon/asgi/stream.py
- falcon/asgi/structures.py
- falcon/request.py
- falcon/response.py
- falcon/routing/compiled.py
- falcon/testing/helpers.py
- falcon/util/misc.py
Here's another round of ASGI-related doc improvements. This one centers mostly on things related to `Request` and `Response`.
#1358
> doc(asgi): Another round of doc updates, this time centered around Request/Response

- falcon/media/multipart.py
Also adapt [`MultipartParseError`](https://falcon.readthedocs.io/en/latest/api/multipart.html#parsing-errors) to use keyword-based HTTPError parameters.
> docs(multipart): document the forgotten BodyPart.name property

- falcon/asgi/structures.py
- tests/asgi/test_sse.py
This patch modifies the SSEvent initializer so that it explicitly checks whether a parameter is None. This avoids the problem of a parameter value having the wrong type, but being evaluated as falsey and thereby bypassing the type check.
#1358
> fix(SSEvent): Parameter validation in the constructor is too lenient

- docs/api/multipart.rst
In this patch, I reordered the clauses in the first sentence of the first note in the multipart forms overview and made a few other minor edits for clarity and correctness.
#953
> doc(multipart): Edit note re how the request body is consumed

- falcon/asgi/request.py
- falcon/request.py
- tests/asgi/test_request_asgi.py
- tests/test_media_handlers.py
This patch adds back support for the media property to help make the ASGI
and WSGI interfaces as similar as possible.
#1358
> refactor(asgi.Request): Change the media property to an alias of get_media()

- falcon/asgi/stream.py
- falcon/errors.py
- tests/asgi/test_boundedstream_asgi.py
This patch does three things to make BoundedStream more robust and debuggable:
1. Disallow re-iteration over the stream when an iteration is already in progress.
2. Yield anything in the buffer first, before awaiting additional body events,
when iterating over a stream that was partially read before the iteration
began.
3. Introduce a custom subclass of ValueError, OperationNotAllowed, that
can be raised to give the developer a more obvious hint as to what
went wrong.
#1358
> fix(asgi.BoundedStream): Mixing iteration and read() can lead to subtle errors

- docs/conf.py
detect windows before setting fork in sphinx config
> chore(sphinx): windows does not support fork

- docs/_static/custom.css
- docs/api/app.rst
- docs/api/cookies.rst
- docs/api/errors.rst
- docs/api/hooks.rst
- docs/api/media.rst
- docs/api/middleware.rst
- docs/api/multipart.rst
- docs/api/redirects.rst
- docs/api/request_and_response_asgi.rst
- docs/api/request_and_response_wsgi.rst
- docs/api/routing.rst
- docs/api/status.rst
- docs/api/testing.rst
- docs/api/util.rst
- docs/index.rst
- falcon/testing/helpers.py
This patch further improves the ASGI docstrings. It also attempts to make navigating long doc pages easier, now that they are starting to become unwieldy with all the additional classes and functions.
#1358
> docs(asgi): Improve docstrings, navigation

- docs/_static/custom.css
- docs/api/cookies.rst
- docs/api/cors.rst
- docs/api/errors.rst
- docs/api/media.rst
- docs/api/middleware.rst
- docs/api/multipart.rst
- docs/api/request_and_response.rst
- docs/api/request_and_response_asgi.rst
- docs/api/request_and_response_wsgi.rst
- docs/api/routing.rst
- docs/api/status.rst
- docs/api/testing.rst
- docs/api/util.rst
- docs/conf.py
- docs/user/faq.rst
- docs/user/tutorial.rst
- falcon/errors.py
- falcon/media/handlers.py
- falcon/media/validators/jsonschema.py
- falcon/testing/__init__.py
- falcon/testing/resource.py
- falcon/testing/test_case.py
- falcon/util/structures.py
- requirements/docs
This PR includes a number of updates to the reference pages in the docs to bring them up to date with ASGI and other code changes since 2.0. 
Outstanding 3.0 doc updates not covered by this PR:
* ASGI tutorial
* Final multipart docs
* WebSocket docs (if that feature does not get postponed to 3.1)
> doc: Bring all reference pages up to date

- .travis.yml
Our `s390x` gate stopped working on Travis, probably because of: https://travis-ci.community/t/s390-xenial-builds-fail-with-an-error-occurred-while-generating-the-build-script/9039
However, it seems that unfortunately all distributions are affected; `s390x` is plainly broken on Travis at the time of writing. Let's disable the gate until it's fixed.
> chore(Travis): temporarily disable the broken s390x gate

- .travis.yml
While at it, migrate to Ubuntu Bionic (18.04) for all Linux gates except the CPython 3.5.2 one.
Also try bumping up PyPy to PyPy 7.3.1 & partially address #1724 by proposing a CPython 3.9-dev gate.
> chore(Travis CI): try resurrecting the IBM Z (s390x) gate

- docs/_newsfragments/1594.bugfix.rst
- falcon/util/uri.py
- tests/test_utils.py
I was benchmarking bytestring concatenation in 2D for both the number of items and the total concatenated string length on both PyPy3 and CPython3.8. Considering a large number of percent-encoded characters to be a bit of an edge case, I decided not to overengineer this, and went on to pick one good "allrounder" per platform.
Closes #1594
> perf(uri.decode): make sure bytestring concatenation is O(n)

- docs/_newsfragments/1135.newandimproved.rst
- falcon/app.py
- falcon/response.py
- falcon/util/misc.py
- tests/test_httpstatus.py
- tests/test_utils.py
> feat(Response): support setting Response.status to http.HTTPStatus

- docs/api/middleware.rst
Just a short documentation typo fix.
I've just noticed that github from the website does not place the branch on my fork. Sorry about that
> docs(middleware): fix typo in middleware

- tests/asgi/test_buffered_reader.py
- tests/test_wsgi.py
Also borrow WSGI server warm-up logic from the _look_ tutorial tests.
> test: tweak complexity to account for PYTHONASYNCIODEBUG slowness

- .github/workflows/tests.yaml
Our `py35` environment seems to error out on GH Actions, see also: https://github.com/pypa/setuptools/issues/2356
However, I noticed that using `tox` and `virtualenv` from `python3.8` works locally on my workstation. Trying that on Actions...
> chore(Actions): try working around broken setuptools 50.0.0 on CPython 3.5.2

- falcon/response_helpers.py
- tests/test_headers.py
When `dowloadable_as` was updated to handle unicode in filenames in https://github.com/falconry/falcon/pull/1750 a bug was introduced when the file has unicode character and a has comma in them.
This fixes the bug by escaping also the commas.
Closes https://github.com/falconry/falcon/issues/1749 (again)
> fix(Response.downloadable_as): properly handle comma in unicode filenames

- falcon/app.py
- falcon/testing/client.py
- falcon/testing/helpers.py
- tests/asgi/_asgi_test_app.py
- tests/asgi/test_scope.py
- tests/asgi/test_testing_asgi.py
- tests/test_alias.py
- tests/test_testing.py
Added `cookies` kwarg to async `simulate_request` function, now a user able to pass cookies to the simulated request.
e.g
```python
response = test_client.get('/', cookies={'foo': 'bar'}
class CustomCookies:
def items(self):
return [('foo', 'bar')]
response = test_client.get('/', cookies=CustomCookies())
```
Follow up for the #1715 PR.
- [] Prefixed code comments with GitHub nick and an appropriate prefix.
- [] Added docstrings for any new classes, …
> feat(testing): Added cookies kwarg to async simulate_request function

- docs/_newsfragments/1779.bugfix.rst
- falcon/routing/compiled.py
- tests/test_default_router.py
The compied router now sets the params only when it matches a route. The generated code looks like this https://gist.github.com/CaselIT/8bc22a248b6c71c89940676d2e86b344
Fixes #1779
> Fix compiler router setting erroneous params

- .github/workflows/create-wheels.yaml
- requirements/tests
This pr should fix the errors in https://github.com/falconry/falcon/actions/runs/393277790
In particular:
- install setuptools >= 44 everywhere
- do not install daphne on windows since it's not used and twisted seem not to compile on py39
- pin `cryptography<3.2` to avoid errors due to old version of open-ssl
> Try fixing wheel builds

- .github/workflows/create-wheels.yaml
- .github/workflows/tests-emulated.yaml
- .github/workflows/tests.yaml
- requirements/tests
- tests/asgi/test_asgi_servers.py
- tests/asgi/test_ws.py
- tests/test_media_handlers.py
- tox.ini
- Move daphne to a tox env
- Use tox to check the wheels reducing duplication
fixes #1795
> chore: use tox to run wheel tests. make daphne optional when testing

- docs/_newsfragments/1801.misc.rst
- docs/api/request_and_response_asgi.rst
- docs/api/request_and_response_wsgi.rst
- falcon/response.py
- tests/test_headers.py
Rename add_link to append_link for accuracy and consistency.
#1801
> refactor(Response): rename add_link to append_link

- docs/_newsfragments/1607.bugfix.rst
- tests/test_response_body.py
This patch aims to wrap up #1607 which seems to have already been fixed earlier:
* Add a Towncrier news fragment
* Add regression tests explicitly targeting the scenario in question
Closes #1607
> fix(App): cement the fact that body serialization error handling has been fixed

- falcon/app.py
- falcon/asgi/app.py
- tests/test_inspect.py
- tests/test_sinks.py
> feat(App): validate that sink methods follow the app's concurrency model (when possible)

- docs/_newsfragments/1358.breakingchange.rst
- falcon/testing/client.py
- falcon/testing/helpers.py
- tests/asgi/test_testing_asgi.py
- tests/test_request_attrs.py
- tests/test_testing.py
- tests/test_utils.py
Revert the change to not set a default User-Agent string on the WSGI side, and implement it for ASGI as well.
> feat(testing): set default User-Agent string for simulated requests

- falcon/asgi/request.py
- falcon/request.py
Funnily enough, Debian is shipping a patch to fix our misspelling.
`debian/patches/fix-spelling.patch`
```
Description: Fix spelling
Author: Thomas Goirand <zigo@debian.org>
Forwarded: no
Last-Update: 2016-07-11
```
Thanks @thomasgoirand ! Don't hesitate to pipe these patches to us!
> docs(Request): integrate a spelling fix by Debian maintainers

- .github/workflows/create-wheels.yaml
- .github/workflows/tests.yaml
- CONTRIBUTING.md
- tools/mintest.sh
- tox.ini
See also: https://github.com/tox-dev/tox/issues/1777
> chore: pin tox to work around 3.21 bug

- docs/_newsfragments/1822.breakingchange.rst
- docs/conf.py
- docs/ext/private_args.py
- falcon/__init__.py
- falcon/app_helpers.py
- falcon/asgi/app.py
- falcon/asgi/multipart.py
- falcon/asgi/request.py
- falcon/asgi/response.py
- falcon/bench/bench.py
- falcon/constants.py
- falcon/media/base.py
- falcon/media/handlers.py
- falcon/media/json.py
- falcon/media/msgpack.py
- falcon/media/multipart.py
- falcon/media/urlencoded.py
- falcon/request.py
- falcon/response.py
- falcon/util/misc.py
- falcon/util/uri.py
- tests/asgi/test_response_media_asgi.py
- tests/asgi/test_sse.py
- tests/test_httperror.py
- tests/test_media_handlers.py
- tests/test_media_urlencoded.py
- tests/test_query_params.py
- tests/test_response_body.py
- tests/test_utils.py
This patch optimizes the media (de)serialization paths for ASGI apps by
avoiding an extra await and slightly flattening the call stack.
BREAKING CHANGE: Private member variables for the default media handlers were
renamed. This should only affect subclasses, as these variables were never
documented, and were not intended to be part of the public interface.
#1822
If you have *any* questions to *any* of the points above, just **submit and ask**! This …
> perf(asgi): Optimize media (de)serialization

- setup.py
It is sad having to resort to this, but it seems that cythonized coroutines, although reasonably sped up as if added directly to an async loop, suffer a severe performance hit when `await`ed from a Python coroutine (and that is what virtually all ASGI app servers out there seem to do). So much that performance deteriorates to worse than pure Python :grimacing: 
Cython 3.0 alpha shows slighty better results, but still not even demonstrably faster than the pure Python version.
> perf: undo ASGI cythonization

- .github/workflows/create-wheels.yaml
- .github/workflows/tests-emulated.yaml
- .github/workflows/tests.yaml
- requirements/docs
- tools/mintest.sh
Wrestle CI issues:
* Pin Sphinx to disallow the latest version (3.5.0) that's breaking the viewcode extension: https://github.com/sphinx-doc/sphinx/issues/8880.
* Work around `codecov` issues detecting the commit hash: https://github.com/codecov/codecov-action/issues/190.
* Unpin `tox` since the related issue has been fixed.
> chore(CI): work around Sphinx and codecov-action issues

- falcon/asgi/_request_helpers.py
- falcon/asgi/request.py
- tests/test_headers.py
- tox.ini
Avoid decoding of header names when possible, and delay value decoding until
it is necessary.
This should reduce the overhead for constructing Request
objects without significantly increasing overall application performance in
the common case, since we reason that applications do not typically access
all request headers that may be present.
The worst case scenario would be an app that accesses the same header more than
a couple of times, in which case we would have to decode said header multiple
times. If this turns out to be a common use case, we will need to look into
memoization or some other mitigation.
#1822 
This is just a reminder about the most common mistakes.  Please make sure that you tick all *appropriate* boxes.  But please read our [contribution guide](../CONTRIBUTING.md) at …
> perf(asgi): optimize request header decoding

- .github/workflows/create-wheels.yaml
- .github/workflows/scripts/verify_tag.py
- tox.ini
https://github.com/actions/upload-release-asset is discontinued, and I've found a better action to upload the asset to the release.
it also allows us to dry things quite a bit
> dry create wheel workflow using a better action to upload wheels to release

- tests/test_wsgi_servers.py
The server startup and teardown machinery in `tests/test_wsgi_servers.py` had a couple of PEBCAKs, plus I was able to reproduce occasional hanging of Meinheld workers.
This patch attempts to rectify these issues, and use Gunicorn's standard machinery to terminate unresponsive workers.
> tests: make WSGI server tests more resilient

- AUTHORS
- docs/changes/3.0.0.rst
I've simply patched up the list by hand.
We have a task to properly automate this for 3.1.
> docs(AUTHORS): include new contributors since 3.0.0a1

- docs/user/faq.rst
The biggest issue was referencing the now-removed ``resp.stream_len``.
> docs(faq): revise the Content-Length FAQ item

- docs/_newsfragments/1902.rst
- falcon/api_helpers.py
- falcon/app_helpers.py
- tests/test_deprecations.py
Re-add removed api_helpers package
closes #1902
> fix(api_helpers): re-add falcon.api_helpers

- docs/_newsfragments/1902.bugfix.rst
- docs/_newsfragments/1911.bugfix.rst
- falcon/asgi/_request_helpers.py
- falcon/asgi/request.py
- falcon/asgi/response.py
- falcon/cyutil/misc.pyx
- falcon/testing/helpers.py
- falcon/util/misc.py
- tests/test_headers.py
> fix(ASGI): assume ISO-8859-1 for ASGI headers 

- requirements/tests
Remove duplicate listing of httpx and uvicorn in test deps.
n/a
> chore: remove duplicate test deps

- setup.py
Prevent the top-level `examples` package from being installed to sitedir.
N/A
> fix: prevent "examples" from being installed as top-level pkg

- docker/Makefile
- docker/bench_py3.Dockerfile
- docker/bench_py3_cython.Dockerfile
Updated docker scripts to generate new images and push to docker hub:
https://hub.docker.com/repository/registry-1.docker.io/falconry/falcon-bench/tags?page=1&ordering=last_updated&name=3.0.1
> chore: update docker images

- tests/test_deps.py
> chore(CI): check vendored mimeparse (as opposed to any external modules)

- docs/user/tutorial-asgi.rst
- examples/asgilook/requirements/asgilook
aioredis 2 instroduces breaking changes. 
I've just constrained it to <2 to fix the tests
I've opened https://github.com/falconry/falcon/issues/1938 to add support for v2 instead
> test: constrain aioredis to <2 in example requirements.

- tests/test_utils.py
Simply re-enable a commented test since the bug was fixed
Fixes #1940
> test: re-enable commented out test

- docs/user/faq.rst
https://github.com/falconry/falcon/discussions/1981#discussioncomment-1544203
Add a faq item based on @vytas7 answer at https://github.com/falconry/falcon/discussions/1981#discussioncomment-1544203
> docs(FAQ): add a FAQ entry based on @vytas7 discussion answer

- docs/_newsfragments/1991.newandimproved.rst
- falcon/app.py
- falcon/routing/static.py
- tests/test_static.py
- tests/test_wsgi_servers.py
Also fix range request support across different WSGI servers by always providing a Python wrapper without a file descriptor, since many `sendfile` implementations are buggy wrt not respecting the current file offset; both Gunicorn (https://github.com/benoitc/gunicorn/issues/2669) and uWSGI are affected according to my testing.
There is still an open question remaining what to do with Meinheld: I've filed this as a separate issue (#1992).
> feat(static): set `Content-Length` for static file responses

- docs/_newsfragments/1963.bugfix.rst
- falcon/routing/static.py
- tests/test_static.py
Implement `close()` method for `_AsyncFileReader`
Fixes #1963 
> fix: implement `close()` method for asgi static files

- README.rst
- docs/index.rst
- docs/user/tutorial-asgi.rst
I was thinking it would be good to expand Quick Links to shorten time-to-FAQ for our repository's guests.
However, it doesn't look perfect: https://github.com/vytas7/falcon/tree/misc-docs-tweaks-2021-12#quick-links
(Suggestions are very welcome. I tried a nested list, and it looked odd with a dark GH theme.)
Or could we maybe add these items inside parentheses on the same line?
> docs: tweak misc stuff, expand quick links

- requirements/tests
Restore `uvicorn` functional tests targeting Python 3.6 (using an older `uvicorn` version).
See also:
* https://github.com/falconry/falcon/pull/2004#discussion_r785427351
* https://github.com/encode/uvicorn/issues/1327
> chore(requirements): resurrect `uvicorn` tests on Python 3.6

- falcon/app.py
- falcon/asgi/stream.py
- falcon/bench/bench.py
- falcon/util/__init__.py
- tests/asgi/test_asgi_servers.py
- tests/asgi/test_boundedstream_asgi.py
- tests/test_buffered_reader.py
- tests/test_media_multipart.py
- tests/test_utils.py
- tests/test_wsgi_servers.py
- tox.ini
It seems that `black` has finally turned stable, which also brings the usual assortment of formatting changes.
> chore: the new `black` is the new black

- docs/_newsfragments/2010.newandimproved.rst
- falcon/util/deprecation.py
- tests/test_utils.py
The deprecated args warning does not tell the function name which is then very hard to debug.
Closes #2010 
> feat(deprecation): add `__qualname__` to deprecated args warnings

- AUTHORS
- docs/changes/3.1.0.rst
- tools/add_contributors.py
Closes #1533
Actually running this tool should be done as part of the release process. I added a mention in #473.
We could probably add a check in CI for pre-release tags... but I left that as a future exercise for now.
Another limitation that we could hopefully live with for a while is that only the primary author with a GitHub login is considered, so commits made by multiple first-time contributors in a single PR might still need a manual review.
> chore(tools): add a tool to aggregate contributors from GitHub commits

- tests/asgi/test_asgi_servers.py
Test that in the absence of chunked `Transfer-Encoding` Falcon correctly handles server-side chunking due to flow control (e.g. https://github.com/encode/uvicorn/blob/90acede056f75a337ef023c4ae335d0d6e33d142/uvicorn/protocols/http/flow_control.py#L13).
> test(asgi): correctly read large bodies chunked server-side

- .github/workflows/test-mailman.yaml
- .github/workflows/tests-mailman.yaml
- .github/workflows/tests.yaml
- tools/testing/fetch_mailman.sh
This pull request adds a GNU Mailman 3 CI gate that is proposed to be run on every `master` merge. Upon every run, Mailman Core is cloned from GitLab, its `tox.ini` patched to add an additional `falcon` env where we simply uninstall Falcon and reinstall it from local source (effectively building a cythonized PEP 517 wheel).
~~A successful run is demoed here: https://github.com/falconry/falcon/runs/5279630719?check_suite_focus=true~~
The following concessions had to be made, because of the way the things are, my incompetence, or a combination thereof:
* ~~I couldn't use @maxking 's Docker image, because GitHub Actions seem to be very hostile to setting a non-root `USER`.~~
* I wished to run tests for a stable release of Mailman instead of the latest `master` commit. However, it seems that …
> chore(mailman): gate non-breaking releases on GNU Mailman 3

- CONTRIBUTING.md
- tests/asgi/_asgi_test_app.py
- tests/asgi/test_asgi_servers.py
This patch adds a check to `test_post_read_bounded_stream_large()` to validate the digest of the body to ensure that the chunks are read completely with no overlap or repetition.
> test(test_post_read_bounded_stream_large): validate body digest

- docs/user/faq.rst
- falcon/media/json.py
Adds an example on how to override the default json encoder used by Falcon.
> docs(media): add an example for using a custom JSON encoder

- AUTHORS
- RELEASE.md
- docs/_newsfragments/1320.newandimproved.rst
- docs/_newsfragments/1806.newandimproved.rst
- docs/_newsfragments/1858.newandimproved.rst
- docs/_newsfragments/1943.bugfix.rst
- docs/_newsfragments/1951.newandimproved.rst
- docs/_newsfragments/1962.newandimproved.rst
- docs/_newsfragments/1963.bugfix.rst
- docs/_newsfragments/1967.misc.rst
- docs/_newsfragments/1991.newandimproved.rst
- docs/_newsfragments/2010.newandimproved.rst
- docs/_newsfragments/2024.bugfix.rst
- docs/changes/3.1.0.rst
- setup.cfg
- tools/towncrier_draft.py
- tox.ini
Add RELEASE.md and prep for 3.1.0rc1
> chore: prep for 3.1.0 release

- .github/workflows/create-wheels.yaml
- requirements/tests
Trying to fix the following issues highlighted by the [failed 3.1.0rc1 build](https://github.com/falconry/falcon/runs/5541468531?check_suite_focus=true):
* `rapidjson` doesn't build on some EoL interpreters
* `orjson` doesn't ship ARM wheels, and rust isn't installed
* Bash script in Actions doesn't properly extract `3.10` from `cp310-cp310`
> chore(wheel): attempt to fix some issues found in 3.1.0rc1 build

- docs/_static/custom.css
- requirements/docs
- tox.ini
Tested on Firefox, Brave, Safari. Also Brave w/ Dark Reader.
> docs: fix up sphinx tabs 🌚

- docs/_newsfragments/2047.bugfix.rst
- examples/look/tests/conftest.py
- tests/asgi/test_asgi_servers.py
- tests/test_wsgi_servers.py
Spawn the servers (gunicorn, uvicorn, etc.) during tests through
sys.executable rather than directly, in order to ensure that the test
server is run using the same Python executable as the test suite.
Otherwise, the test servers are started using the Python executable
specified in their shebang and can therefore escape the virtualenv they
are being run in.
This is particularly problem for tests being run from Gentoo ebuilds.
We create a --system-site-packages venv to install falcon in, in order
to test whether it works correctly against the dependencies installed
on the system prior to installing it.  However, the installed packages
such as gunicorn specify /usr/bin/python* shebangs that override
the venv and therefore make these servers unable to find venv-installed
falcon.  Running them …
> fix(tests): spawn servers via sys.executable

- docs/conf.py
This classical `conf.py` hack shouldn't really be needed, but apparently in some scenarios it is still desirable. Shouldn't hurt for anybody else.
Closes #2080
> chore: insert parent dir into `sys.path` when building docs

- docs/api/testing.rst
- docs/user/faq.rst
- falcon/media/json.py
- tox.ini
Add a note that `TestClient`'s `simulate_*()` methods don't use the app's media handlers.
Closes #2099
An unrelated change to get the CI to pass: Hypercorn is pinned in the corresponding `tox` environment to exclude the current buggy versions (ref https://github.com/pgjones/hypercorn/issues/65).
> docs: clarify that `TestClient` doesn't use the app's JSON handlers

- docs/_newsfragments/2100.bugfix.rst
- falcon/media/json.py
- tests/test_media_handlers.py
> fix(asgi.App): correctly pass params when using `orjson.dumps`

- AUTHORS
- docs/_newsfragments/2108.newandimproved.rst
- falcon/asgi/app.py
- falcon/asgi/response.py
- falcon/http_error.py
- falcon/http_status.py
- falcon/response.py
- falcon/util/misc.py
- tests/test_error_handlers.py
- tests/test_http_custom_method_routing.py
- tests/test_httperror.py
- tests/test_httpstatus.py
- tox.ini
This patch adds a status_code attribute (property) to the Response, HTTPError,
and HTTPStatus classes to afford introspection by middleware and error
handlers.
> feat: status_code attribute for Response, HTTPError, HTTPStatus

- falcon/bench/dj/dj/urls.py
Running docker bench_py3.Dockerfile ends with error:
```
File "/usr/local/lib/python3.8/site-packages/falcon/bench/dj/dj/urls.py", line 1, in <module>
from django.conf.urls import url
ImportError: cannot import name 'url' from 'django.conf.urls' (/usr/local/lib/python3.8/site-packages/django/conf/urls/__init__.py)
```
> django.conf.urls.url() was deprecated in Dj 3.0, and is removed in Dj 4.0+

- setup.py
- tox.ini
There is a typing issue in `FloatConverter` that is causing problems during runtime, and would be detected in `mypy` too.
This is fixed in my typing branch, but I just backported a simple switch not to enforce types in Cython since that has been observed to actually be a de-optimization in most cases.
The problem has been masked by another issue that our Cython gates have PEP 517 disabled in `tox`, however, the Cython dependency is not installed into these.
> fix(Cython): re-enable cythonization in Cython gates, do not enforce typing

- docs/_newsfragments/2060.newandimproved.rst
- falcon/request.py
- tests/test_headers.py
Implements the `get_header_as_int` method.
Wasn't sure whether (and how) to document it in the docs, as I couldn't find the part for the similar function `get_header_as_datetime()`.
#2060
> refactor: implement `get_header_as_int` method

- .github/workflows/create-wheels.yaml
- README.rst
- RELEASE.md
(As in the previous similar 3.1.1 PR, some checks are marked as waiting forever because the job definitions have changed since. But all checks do pass.)
> chore(3.1.1): misc polish post-3.1.1b1

- .github/workflows/create-wheels.yaml
- RELEASE.md
Closes #473
(The `RELEASE.md` document that we currently have isn't perfect, but it does the job... so let's close the issue and keep improving it as we go.)
> docs(release): backportport misc `RELEASE.md` improvements from 3.1.1

- tox.ini
`flake8-import-order` has just been updated with support for v6.0, however, `flake8-quotes` is, at the time of this writing, still incompatible: https://github.com/zheller/flake8-quotes/issues/110.
> chore(PEP8): pin `flake8` until its plugins have caught up

- .devcontainer/devcontainer.json
- CONTRIBUTING.md
This adds the required config for VS Code [Dev Container](https://code.visualstudio.com/docs/devcontainers/containers) support. With this change, opening the repo in VS Code will prompt you to reload the editor and, assuming you have Docker up and running, it will pull the required Docker image and start it. Expect it to download a 1.4GB image. Once the container is running, it will install a bunch of dependencies, including `tox`. It will show you the log as it progresses, but, at the end of the process, VS Code will run in this container in headless mode and you can open a separate terminal in which you can run the `tox` command which should complete successfully.
I haven't spotted any specific section related to the code editor in the Readme / Contributing docs, so not sure if you'd …
> chore: add VS Code dev container

- .github/workflows/tests-mailman.yaml
- tools/testing/fetch_mailman.sh
Trying various options to address this CI failure: https://github.com/falconry/falcon/actions/runs/3557778912/jobs/6035948328:
```
FAIL: test_uheader_multiline (mailman.handlers.tests.test_cook_headers.TestCookHeaders)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/github/workspace/.ecosystem/mailman/src/mailman/handlers/tests/test_cook_headers.py", line 65, in test_uheader_multiline
self.assertEqual(header.encode(), 'A multiline [...]')
AssertionError: '=?utf-8?b?QSBtdWx0aWxpbmUgWy4uLl0=?=' != 'A multiline [...]'
- =?utf-8?b?QSBtdWx0aWxpbmUgWy4uLl0=?=
+ A multiline [...]
```
> chore(CI): attempt to fix the Mailman CI gate

- falcon/forwarded.py
Simple one word change in source note about a field name 
> docs(Forwarded): update note in forwarded.py

- docs/_newsfragments/2146.bugfix.rst
- falcon/asgi/app.py
- falcon/asgi/ws.py
- falcon/util/misc.py
- tests/asgi/test_misc.py
- tests/asgi/test_ws.py
- tests/test_utils.py
Can you think of further tests to try?
Fixes #2146
> fix(WebSocket): properly handle HTTPStatus and HTTPError cases

- falcon/stream.py
- pyproject.toml
> feat: Add type hints to stream module

- falcon/util/__init__.py
- falcon/util/deprecation.py
- falcon/util/misc.py
- falcon/util/reader.py
- falcon/util/structures.py
- falcon/util/sync.py
- falcon/util/uri.py
- pyproject.toml
> feat(typing): type util package

- tests/_util.py
- tests/test_uri_converters.py
- tests/test_uri_templates.py
Trying to run `pytest .\tests\ -n 6 --dist=worksteal` on master it results in an error since different test are collected.
This is mostly because we parametrize the test on random uuid, that result in the test signature to be different.
This fixes that by creating a deterministic id for the parametrized test where needed
> chore(testing): allow test to be run using pytest-xdist

- .github/workflows/create-wheels.yaml
- .github/workflows/tests-mailman.yaml
- .github/workflows/tests.yaml
- docs/conf.py
- falcon/inspect.py
- falcon/routing/compiled.py
- falcon/util/misc.py
- pyproject.toml
- setup.cfg
- tests/asgi/test_ws.py
- tests/test_cookies.py
- tests/test_headers.py
- tests/test_middleware.py
- tests/test_request_attrs.py
- tests/test_request_media.py
- tests/test_utils.py
- tests/test_validators.py
- tox.ini
> chore: support CPython 3.12, update CI jobs

- .readthedocs.yaml
It seams that our builds have stopped working completely, Read the Docs now [mandates having a config file](https://blog.readthedocs.com/migrate-configuration-v2/):
```
Error
Problem in your project's configuration. No default configuration file found at repository's root.
```
> chore(readthedocs): add `.readthedocs.yaml` as required

- docs/conf.py
(As it links to a removed S3 object.)
See also: https://github.com/sphinx-doc/alabaster/issues/166.
> chore(alabaster): disable GitHub banner

- falcon/app.py
- tests/test_error_handlers.py
- tests/test_middleware.py
We should have added this warning already in 2.0, but the invocation of that shim is still silent :slightly_frowning_face: This PR aims to rectify that, and warn users about using an support call signature.
> feat(add_error_handler): deprecate the Falcon 1.x signature shim

- .github/workflows/mintest.yaml
- docs/conf.py
- docs/ext/rfc.py
- falcon/asgi/ws.py
- falcon/media/handlers.py
- falcon/testing/helpers.py
- tests/asgi/test_ws.py
Closes #2179
An example of a passing CI gate: https://github.com/falconry/falcon/actions/runs/7160503496/job/19494950553.
> chore:  make contributor's checklist pass on CPython 3.12

- docs/_newsfragments/1977.breakingchange.rst
- docs/api/cors.rst
- falcon/app.py
- tests/test_middleware.py
> feat(cors): disallow `cors_enable` & additional `CORSMiddleware` combo

- docs/_newsfragments/1999.breakingchange.rst
- falcon/cyutil/uri.pyx
- falcon/util/uri.py
- tests/test_utils.py
> feat(parse_query_string): change the default value of `csv` to `False`

- docs/user/faq.rst
> docs(FAQ): add a FAQ item on shutting down `wsgiref.simple_server`

- docs/user/tutorial-asgi.rst
- examples/asgilook/asgilook/cache.py
- examples/asgilook/asgilook/config.py
- examples/asgilook/requirements/asgilook
As of Feb 21, 2023 aioredis-py was archived. See the package repo here:
https://github.com/aio-libs-abandoned/aioredis-py
A docs update to correct the ASGI doc to use the latest version of Redis and swap the `aioredis` package for the `redis` package since `aioredis` is now included within `redis`.
- [X ] Added **tests** for changed code.
- [ X] Prefixed code comments with GitHub nick and an appropriate prefix.
- [ X] Coding style is consistent with …
> chore: update to latest Redis (aioredis is deprecated)

- falcon/util/sync.py
- pyproject.toml
- requirements/tests
- tests/asgi/test_asgi_servers.py
- tests/asgi/test_scope.py
- tests/dump_asgi.py
> chore(sync): use `asyncio.Runner` for `async_to_sync()` on py311+

- README.rst
- docs/_newsfragments/2066.newandimproved.rst
- docs/api/util.rst
- docs/user/recipes/pretty-json.rst
- falcon/__init__.py
- falcon/asgi/multipart.py
- falcon/media/multipart.py
- falcon/testing/helpers.py
- falcon/util/__init__.py
- falcon/util/mediatypes.py
- falcon/vendor/mimeparse/mimeparse.py
- pyproject.toml
- tests/test_mediatypes.py
I have another branch which also introduces Cython's "pure Python mode" in order to speed up `parse_header()`, but we can circle back on that optimization in Falcon 4.1.
I'm also planning to reimplement the parts of `mimeparse` that we actually use, and unvendor it completely.
Fixes #2066
> feat(parse_header): provide our own implementation of `parse_header()`

- falcon/util/structures.py
This change affords arbitrary attribute access for `req.context` & `resp.context` in typed code without having to mask Mypy warnings similar to `error: "Context" has no attribute "..."`.
> chore(typing): add more descriptive typing to `Context`

- .github/workflows/tests.yaml
- CONTRIBUTING.md
- docs/changes/4.0.0.rst
- tox.ini
> chore: make CPython 3.12 default CI version

- tox.ini
> chore(tox): drop `--no-build-isolation` from Cython tests

- docs/user/tutorial-asgi.rst
- examples/asgilook/asgilook/store.py
- requirements/tests
- tox.ini
It seems that something breaks when using `testtools.TestCase` under `pytest` 8.2.x along the lines of https://github.com/pytest-dev/pytest/issues/12263. This PR temporarily pins `pytest` until the issue is resolved upstream, or we decide on how we want to move forward with this. An alternative is to drop active support for `testtools` altogether: #2156.
Also patched is some typing import issue in ASGI tutorial tests. The issue seems to also stem from third party packages (`fakeredis`) under Python 3.10 that we had hardwired in the tox env by mistake. I'll file a followup issue, because this also means that our tutorial is not fully usable on 3.10 or older.
> chore(CI): pin `pytest` + ASGI tutorial fixes

- docs/user/tutorial-asgi.rst
This PR introduces a new section to the ASGI tutorial in the Falcon documentation, aimed at providing developers with clear instructions on setting up and utilizing logging for debugging ASGI applications. The added content outlines the steps to configure basic logging using Python's built-in logging module, offering examples of how to log informational, warning, and error messages effectively.
#2098 
If you have *any* questions to *any* of the points …
> docs(asgi-tutorial): include info on setting up logging for debugging

- docs/api/util.rst
- docs/user/tutorial-asgi.rst
The broken link itself has been discovered by @e-io.
~~I haven't been able to find what inserts the `_asyncio` module in the index. But it isn't easy to find that index anyway, is it?~~
**Edit**: I've found the culprit for that `_asyncio` in the index. We had aliased functions directly from the stdlib, so I went on to soft-deprecate them for now. I'll create an issue to deprecate them (but there is probably no rush to do so.)
> docs(user, util): address broken links

- .github/workflows/tests-mailman.yaml
- tools/testing/fetch_mailman.sh
Thanks @maxking for maintaining a special Docker image for us. The gate is green again now.
> chore(CI): restore GNU Mailman integration tests gate

- .github/workflows/create-wheels.yaml
- .github/workflows/tests.yaml
- README.rst
- docs/changes/4.0.0.rst
- docs/index.rst
- docs/user/install.rst
- docs/user/intro.rst
- docs/user/recipes/request-id.rst
- docs/user/tutorial-asgi.rst
- falcon/constants.py
- falcon/cyutil/misc.pyx
- falcon/request.py
- falcon/response_helpers.py
- falcon/util/misc.py
- pyproject.toml
- requirements/tests
- setup.cfg
- tests/test_utils.py
- tox.ini
Drop python 3.7. The main reason is the lack of typing.Protocol, complicating typing introduction
> chore: remove python 3.7 support

- .github/workflows/tests-emulated.yaml
A successful run has been demonstrated here: https://github.com/falconry/falcon/actions/runs/10465472709.
> chore(emulated): simplify emulated tests by reusing `cibuildwheel`

- docs/_newsfragments/2124.newandimproved.rst
- docs/_newsfragments/2213.newandimproved.rst
- docs/api/cookies.rst
- docs/api/middleware.rst
- docs/api/redirects.rst
- docs/api/routing.rst
- docs/api/websocket.rst
- docs/changes/0.3.0.rst
- docs/changes/2.0.0.rst
- falcon/app.py
- falcon/asgi/app.py
- falcon/asgi/request.py
- falcon/asgi/response.py
- falcon/asgi/ws.py
- falcon/media/base.py
- falcon/media/json.py
- falcon/media/msgpack.py
- falcon/request.py
- falcon/response.py
- falcon/routing/compiled.py
- falcon/routing/util.py
- falcon/testing/client.py
- falcon/testing/helpers.py
- falcon/testing/resource.py
- falcon/testing/test_case.py
- falcon/util/time.py
This is just a cleanup PR to remove the `:py:target:` marker, since it's not needed and the docs had a mix of styles
NOTE: this PR includes #2271
> docs: normalize Sphinx link markers

- docs/_newsfragments/2293.bugfix.rst
- falcon/media/handlers.py
- falcon/media/multipart.py
- tests/test_media_multipart.py
Fix a problem, when MultipartParseOptions._DEFAULT_HANDLERS was shared between different instances
Fixes #2293.
- [] Updated **documentation** for changed code.
> fix(multipart): don't share MultipartParseOptions._DEFAULT_HANDLERS

- docs/_newsfragments/2343.breakingchange.rst
- falcon/hooks.py
- falcon/media/validators/jsonschema.py
- tests/asgi/_cythonized.pyx
- tests/asgi/test_cythonized_asgi.py
- tests/test_after_hooks.py
- tests/test_before_hooks.py
> chore: remove `is_async` support

- docs/changes/4.0.0.rst
- falcon/asgi/multipart.py
- falcon/media/multipart.py
- tests/test_media_multipart.py
> fix(multipart): do not require CRLF after the closing delimiter

- .github/workflows/test-dist.yaml
- .github/workflows/tox-sdist.yaml
- docs/_newsfragments/2384.bugfix.rst
- pyproject.toml
- tools/test_dist.py
> fix(dist): only detect `falcon*` as packages

- docs/_newsfragments/2387.misc.rst
- falcon/testing/__init__.py
... so mypy also likes it when falcon.testing.TestClient is used
#2387 
> fix: explicitly export the items in the falcon.testing namespace

- .github/workflows/cibuildwheel.yaml
For 4.0, the setup was the opposite, and that was deliberate -- we waited for all wheels in order to publish anything to PyPI.
However, now that we have a CI gate testing a representative selection of wheels, we should afford to publish sdist first, and then hope that the binary builds succeed too.
> chore: publish sdist & pure-Python wheel without waiting for binaries

- requirements/tests
- tests/asgi/test_asgi_servers.py
I have upgraded our server tests to the [new `websockets` async client interface](https://websockets.readthedocs.io/en/latest/reference/asyncio/client.html).
(I also filed a minor documentation issue: https://github.com/python-websockets/websockets/issues/1537.)
**Edit**: the tests now pass on Uvicorn, Daphne, and Hypercorn.
> chore(tests/asgi): migrate to the new `websockets` async client

- docs/community/index.rst
- docs/community/packaging.rst
- docs/user/intro.rst
Here's my first stab at creating the packaging guide :sweat_smile:
Closes #2081.
This guide is not aimed at the packaging mechanics of a specific distribution, but rather general guidelines and ideas from our perspective. For reference, we were considering our own Ubuntu/Debian PPA at some point (see #1061 by @jmvrbanac), but it has never materialized, and unfortunately we don't really have the bandwidth for that kind of project.
We do want to make a packager's life easier as much as we can though (not just giving a :middle_finger: pointing to our CI as some other Python project maintainers do that we won't name here _cough_), and I hope 4.0.0 was a step in the right direction.
We sincerely appreciate the work that you put into maintaining Falcon package for various Linux distributions, …
> docs(community): write a guide for packaging Falcon

- .github/workflows/tests.yaml
- docs/api/cookies.rst
- falcon/util/__init__.py
- requirements/tests
This PR implements rudimentary support for CPython 3.14, adapting our monkey-patching of `Morsel` attributes to a new optimization in 3.14 stdlib.
In addition, the monkey patching of the `SameSite` attribute was removed, since it is no longer needed on 3.8+.
(See also Red Hat Bugzilla: [Bug 2328020](https://bugzilla.redhat.com/show_bug.cgi?id=2328020). @befeleme @carlwgeorge)
> chore: implement initial support for CPython 3.14

- docs/user/recipes/index.rst
- docs/user/recipes/plain-text-handler.rst
- examples/recipes/plain_text_main.py
- tests/test_recipes.py
introduce a new recipe demonstrating a text/plain media handler implementation the recipe includes serialization and deserialization logic, with support for  custom charsets.
Closes #2037
> docs(recipes): add text/plain media handler recipe

- .github/workflows/cibuildwheel.yaml
- .github/workflows/test-wheels.yaml
- falcon/bench/dj/dj/settings.py
- falcon/routing/compiled.py
- falcon/stream.py
- falcon/util/mediatypes.py
- tests/asgi/test_boundedstream_asgi.py
- tests/test_buffered_reader.py
- tests/test_headers.py
- tests/test_middleware.py
- tests/test_recipes.py
- tests/test_utils.py
- tools/add_contributors.py
- tox.ini
Closes #2427.
**Edit**: example of a successful `cibuildwheel` run: https://github.com/falconry/falcon/actions/runs/12854205655/job/35838293754.
> chore(CI): use Linux arm64 hosted runners

- .github/workflows/tests.yaml
- requirements/tests
- tests/asgi/test_asgi_servers.py
Also addressing the recent failure with `websockets==14.2`.
> chore(requirements): unpin some test dependencies

- docs/conf.py
- setup.py
This is in _Draft_ because I might be adding a couple more tweaks.
> chore: apply misc tweaks to cythonization and documentation

- .github/workflows/test-mailman.yaml
- tools/testing/fetch_mailman.sh
I cannot understand how this can possibly pass upstream. One explanation could be that the upstream's gate selection actually doesn't include the same `nocov` environment that we piggyback on.
See also: https://gitlab.com/mailman/mailman/-/issues/1203 (that I filed upstream).
>  chore(CI): comment out one failing doctest for Mailman

- docs/_newsfragments/2244.newandimproved.rst
- docs/api/routing.rst
- falcon/routing/static.py
- tests/test_static.py
- Render `Last-Modified` header for static file responses.
- Check request `If-Modified-Since` header and return 304 if date in this header is not earlier than mtime.
Fixes #2244
> feat(static): implement Last-Modified header for static route

- .github/PULL_REQUEST_TEMPLATE.md
Fix the towncreier link in the PULL_REQUEST_TEMPLATE.
N/A
> docs(pr_template): fix the towncreier link

- docs/_newsfragments/2389.misc.rst
- docs/_newsfragments/2389.newandimproved.rst
- falcon/testing/__init__.py
- tests/test_testing.py
- tests/test_utils.py
Deprecate `falcon.testing.httpnow`.
- fix https://github.com/falconry/falcon/issues/2389
> refactor(testing): deprecate httpnow

- docs/api/media.rst
- docs/user/faq.rst
- docs/user/recipes/index.rst
- docs/user/recipes/msgspec-integration.rst
- examples/recipes/msgspec_json_handler.py
- examples/recipes/msgspec_main.py
- examples/recipes/msgspec_media_validation.py
- examples/recipes/msgspec_msgpack_handler.py
- falcon/media/json.py
- requirements/tests
- tests/test_httperror.py
- tests/test_media_handlers.py
- tests/test_recipes.py
The recipe probably still needs minor polishing, but pushing this out to review anyway -- a fair part of this PR has been sitting in my branches for more than a year :cold_sweat: _Perfect is the enemy of good_, as they say...
> docs(user): add `msgspec` recipe and FAQ answer

- .github/workflows/test-other.yaml
Seems to run just fine, provided we are using an older version of Python (leaving this on 3.8 while we still support it): https://github.com/falconry/falcon/actions/runs/14591904670.
> chore(CI): port legacy gates to Ubuntu 24.04

- docs/_newsfragments/2243.newandimproved.rst
- falcon/routing/static.py
- tests/test_static.py
- Render `Etag` header for static file responses
- Check requests' `If-None-Match` header and return 304 when appropriate.
Fixes #2243
> feat(static): implement Etag and If-None-Match for static route

- docs/_newsfragments/2453.newandimproved.rst
- docs/api/cookies.rst
- falcon/response.py
- tests/test_cookies.py
- Add `same_site` parameter to `Response.unset_cookie()` method for consistency with `Response.set_cookie()` method
- Deprecate the previous `samesite` parameter with a deprecation warning
- Update tests and documentation to use the new parameter name
The `Response.set_cookie()` method uses `same_site` parameter (with underscore) while `Response.unset_cookie()` was using `samesite` parameter (without underscore). This inconsistency made the API confusing to use.
This change:
- Adds `same_site` parameter to `unset_cookie()` for consistency
- Maintains backward compatibility by keeping the old `samesite` parameter
- Emits a `DeprecatedWarning` when the old parameter is used
- Updates all tests to use the new parameter name
- Updates documentation to reflect the change
Closes #2453
> feat(cookies): add same_site parameter to unset_cookie for consistency

- .github/workflows/test-dist.yaml
- RELEASE.md
- docs/changes/1.0.0.rst
- docs/changes/1.1.0.rst
- docs/changes/1.2.0.rst
- docs/changes/1.3.0.rst
- docs/changes/1.4.0.rst
- docs/changes/1.4.1.rst
- docs/changes/2.0.0.rst
- docs/changes/3.0.0.rst
- docs/changes/3.0.1.rst
- docs/changes/3.1.0.rst
- docs/changes/3.1.1.rst
- docs/changes/3.1.2.rst
- docs/changes/3.1.3.rst
- docs/changes/4.0.0.rst
- docs/changes/4.0.1.rst
- docs/changes/4.0.2.rst
- docs/community/coc.md
- docs/community/help.rst
- docs/community/index.rst
- docs/community/packaging.rst
- docs/community/releases.rst
- docs/conf.py
- docs/ext/cibuildwheel.py
- docs/ext/falcon_releases.py
- docs/user/install.rst
- docs/user/intro.rst
- tools/check_dist.py
- tox.ini
As discussed with @CaselIT, we formalized the security maintenance period of the "old stable" series (e.g., Falcon 3.x atm), currently defined as 2 years from the first stable release of the current series.
Closes #2410.
> docs(community): document release maintenance policy

- docs/user/faq.rst
- falcon/util/structures.py
See #1430 for discussion/background.
Closes #1430.
> docs(Context): remove deprecation warnings for the mapping interface

- docs/conf.py
- docs/ext/workarounds.py
See also #2465: it seems that this workaround is still needed after all, or at least I don't know how to make it work properly with, for instance, @jkmnt's aliases from #2390.
> chore(sphinx): monkey-patch textual representation of `TypeAliasForwardRef`

- falcon/testing/client.py
- tests/test_utils.py
Hello! This PR implements `__rich__` method for `testing.Result` which can be used with [rich](https://github.com/Textualize/rich) console/terminal library. 
Improvised a bit, status code and color mapping as following: `1xx` - blue, `2xx` -  green, `3xx` - yellow, `4xx` - magenta, `5xx` - red (rich standard [colors](https://rich.readthedocs.io/en/stable/appendix/colors.html)).
Did some refactoring related to reusability, where some part of the code is used in both `__repr__` and `__rich__`.
<details>
<summary>Code</summary>
```python
from rich import print
import falcon
import falcon.testing
statuses = [
falcon.HTTP_101,
falcon.HTTP_200,
falcon.HTTP_301,
falcon.HTTP_404,
falcon.HTTP_500,
]
for status in statuses:
result = falcon.testing.Result(
[b'salom!'],
status,
[('content-type', …
```
> feat(testing): add rich repr to testing.Result

- .github/workflows/cibuildwheel.yaml
I forgot to actually RT(F)M, it seems. Take two... :crossed_fingers:
> fix(cibuildwheel): fix id-token permissions for Trusted Publishing

- docs/_newsfragments/2381.newandimproved.rst
- falcon/middleware.py
- tests/test_cors_middleware.py
Added support for private networks (`Access-Control-Allow-Private-Network` header). 
I've read referenced [docs](https://wicg.github.io/private-network-access/#headers), where I also found two additional(and optional) headers that I also added support in this PR. From docs:
> * The Private-Network-Access-Name attempts to provide users a human friendly name in the private network access permission prompt.
> * The Private-Network-Access-ID header is used in the [PrivateNetworkAccessPermissionDescriptor](https://wicg.github.io/private-network-access/#dictdef-privatenetworkaccesspermissiondescriptor) to identify identical devices across IP addresses.
They are being validated accordingly as stated in [docs](https://wicg.github.io/private-network-access/#permission-prompt).
Should I update …
> feat(cors): support for private networks in `CORSMiddleware`

- .github/workflows/cibuildwheel.yaml
- .github/workflows/test-wheels.yaml
- .github/workflows/tests.yaml
- docs/ext/cibuildwheel.py
- falcon/cyutil/uri.pyx
- tox.ini
**Note**: it is important not to publish any stable release wheels compiled against a pre-release CPython.
However, the `rc1` is anticipated in ~1 week, so the risk of us ushering a stable release out the door is highly unlikely anyway.
> chore(cibuildwheel): enable CPython 3.14 wheels

- .coveragerc
- .github/workflows/tox-sdist.yaml
- CONTRIBUTING.md
- docs/changes/4.1.0.rst
- falcon/asgi/app.py
- falcon/asgi/reader.py
- pyproject.toml
- requirements/tests
- tests/test_media_handlers.py
- tests/test_recipes.py
Closes #2413.
Tox default environments fully passing on 3.14: https://github.com/falconry/falcon/actions/runs/16320285729/job/46096010573.
> feat(platforms): fully support CPython 3.14

- tests/test_wsgi_servers.py
This PR refactors `tests/test_wsgi_servers.py`  that relied on optional dependencies by replacing manual try-except import with `pytest.importorskip`.
What does `pytest.importorskip` do? 
`pytest.importorskip("module_name")` tries to import a module only if it's available. If it's not, it skips the test automatically with a clear message, instead of failing due to an ImportError.
Benefits:
- Follows pytest best practices for optional imports
- Reduces boilerplate code and duplication
- Makes test behavior more consistent across environments
Also I was novice around this approach so took some help from the LLMs around the globe where I found that,
Using `pytest.importorskip` can reduce the need for linter overrides — especially around:
- F401 (imported but unused)
- E402 (module-level …
> refactor: use `pytest.importorskip` for optional dependency imports

- .github/workflows/test-wheels.yaml
- AUTHORS
- docs/changes/4.1.0.rst
- falcon/version.py
I have successfully built out more CPython 3.14 wheels, so hopefully we can avoid unpleasant surprises later on: https://github.com/falconry/falcon/actions/runs/16409687738.
> chore: prepare 4.1.0a1

- .github/workflows/cibuildwheel.yaml
As pointed out by @webknjaz, the best practice recommended by `pypa/gh-action-pypi-publish` is to expose the created _Trusted Publisher_ OIDC tokens to as few third-party actions as possible.
This changeset aims to address the issue (unless I misunderstood it again :cold_sweat:).
> chore(release): decouple jobs with `id-token` access from other actions

- falcon/asgi/multipart.py
- falcon/media/multipart.py
The current docs show the WSGI MultiPart "in an ASGI application".
N/A
This is just a reminder about the most common mistakes.  Please make sure that you tick all *appropriate* boxes.  Reading our [contribution guide](https://falcon.readthedocs.io/en/stable/community/contributing.html) at least once will save you a few review cycles!
> docs: fix the WSGI MultiPart docstring

- docs/_newsfragments/1169.newandimproved.rst
- falcon/cyutil/uri.pyx
- falcon/util/uri.py
- tests/test_utils.py
The URI encoding functions [encode()](https://falcon.readthedocs.io/en/stable/api/util.html#falcon.uri.encode), [encode_check_escaped()](https://falcon.readthedocs.io/en/stable/api/util.html#falcon.uri.encode_check_escaped), [encode_value()](https://falcon.readthedocs.io/en/stable/api/util.html#falcon.uri.encode_value), and [encode_value_check_escaped()](https://falcon.readthedocs.io/en/stable/api/util.html#falcon.uri.encode_value_check_escaped) have been reimplemented in Cython, leading to a significant speed bump under CPython (provided Falcon is [installed](file:///home/vytas/progs/falcon/docs/_build/html/user/install.html#install) from a binary wheel, or cythonized from a source distribution).
The performance improvement can reach an order of magnitude, although the actual numbers …
> perf(uri): speed up URI encoding by hand-crafted Cython code

- .github/workflows/cibuildwheel.yaml
replace redundant 'pattern' and 'merge-multiple' in upload-sdist and publish-sdist jobs with 'name: cibw-sdist' since sdist is a single artifact. There is no need to merge multiple artifacts.
Closes #2497
This is just a reminder about the most common mistakes.  Please make sure that you tick all *appropriate* boxes.  Reading our [contribution guide](https://falcon.readthedocs.io/en/stable/community/contributing.html) at least once will save you a few review cycles!
> chore(cibuildwheel): simplify sdist artifact download
